### ISSUE TITLE
Build error in embedded webview

### ISSUE THREAD

**Issue by cagataygurturk** [Telerik-Verified-Plugins/WKWebView#100]
I use cordova webview in a larger native app and due to lack of MainViewController class, after installing the plugin it does not build.

**Comment by EddyVerbruggen** [comment]
Hi, when you say 'a larger native app' do you mean it's not a Cordova app? If so, then this plugin will indeed not work.

**Comment by cagataygurturk** [comment]
I just embed uiwebview for some parts of the application (http://docs.phonegap.com/en/4.0.0/guide_hybrid_webviews_index.md.html) and i want to use wkwebview instead of uiwebview but it does not build.

**Comment by EddyVerbruggen** [comment]
And you are using this plugin? Can you share the project perhaps?
