### ISSUE TITLE
Hide scroll bars when scrolling

### ISSUE THREAD

**Issue by Tarang** [Telerik-Verified-Plugins/WKWebView#106]
Is it possible to hide the scroll bars when scrolling. They are hidden on the UIWebview using `overflow: hidden;` but appear when scrolling using the wkWebView plugin

**Comment by EddyVerbruggen** [comment]
Hi, great idea, it even makes sense as default behaviour.

**Comment by EddyVerbruggen** [comment]
It's in master now, and will be part of 0.4.0.
