### ISSUE TITLE
LocalStorage not updated when upgrading app to WKWebView version

### ISSUE THREAD

**Issue by tuomaslaa** [Telerik-Verified-Plugins/WKWebView#107]
It seems that the HTML5 LocalStorage is not updated when upgrading app to WKWebView version.

And if I'am right it tries to copy from UIWebView to WKWebView with every "viewDidLoad" event. One time should be enough.

**Comment by EddyVerbruggen** [comment]
Can you tell me a way to easily reproduce this?

**Comment by kaansoral** [comment]
I implemented an sqlite based backup and restore routine for localStorage, when it detects an empty localStorage, it restores the backed up one from sqlite

the web view storages are certainly not persistent, sometimes updates reset the storage, sometimes android devices get updated webkit's that change the behaviour etc.

better manually persist it

**Comment by tuomaslaa** [comment]
I did more testing and it seems that with the debug version it work but with the release version it will not work. 

I tested it like this:
1) First changed in AppDelegate+WKWebViewPolyfill this line (IsAtLeastiOSVersion(@"9.0")) so it will run with UIWebView
2) Then installed the app 
3) Then changed the line back to (IsAtLeastiOSVersion(@"8.0")) so it will run with the WKWebView

**Comment by tuomaslaa** [comment]
any progress on this issue?

**Comment by EddyVerbruggen** [comment]
Not yet, hopefully this weekend.

**Comment by tuomaslaa** [comment]
Now when I tested it seems that it doesn't work in both debug and release version. I'am just wondering if I forgot to delete the app between two tests last time.

**Comment by rebrandsoftware** [comment]
Same issue for me, anything saved in LocalStorage for UIWebView is not migrated over to WKWebView, and vice versa.  I have two different data sets depending on whether or not the plugin is installed.  

The manual backup is a good idea, but that means I have to implement it and make sure all users have it applied before I can upgrade to WKWebView.  I really have no way to guarantee that.

Can I manually switch between the two?  Always start with UIWebView, make sure to perform a backup, switch to WKWebView, restore a backup if it exists, and stay with WKWebView from then on?

**Comment by tuomaslaa** [comment]
Is there any news on this? 

I was thinking that because this is mainly one time operation only could it be done also only once. Users are not downgrading and can't even downgrade their iOS version. I think copying localStorage on every app load slows the app loading little bit.

**Comment by EddyVerbruggen** [comment]
@tuomaslaa The rationale was folks may decide to remove wkwebview at some point because of potential trouble they run into. Perhaps I was being too careful. Will consider your suggestion!

**Comment by damrbaby** [comment]
I ran into this as well- when updating an existing app that was using UIWebView to an app using WKWebView (via this plugin) localStorage was unfortunately lost :(

**Comment by EddyVerbruggen** [comment]
It seems like LS locations may have been changed recently in iOS, so I'm thinking it's best to offer an option to disable LS as a whole. For new apps it's best to set the new `config.xml` `DisableLocalStorageSyncWithUIWebView` property to `true`, for existing apps where you want users to have their LS migrated you can test with the default settings. Still, if you run into trouble I'd advice you to also set the property to `true`.

Note that if it's `false` (the default, and the same as it was before) LS will be copied back and forth between WK and UI webview every time the app starts/stops. Which I added as a nice feature to be able to downgrade in case of trouble, but it may not be as bulletproof as I hoped.

Available in 0.5.1.
