### ISSUE TITLE
window.openDatabase causes security exception

### ISSUE THREAD

**Issue by shepsii** [Telerik-Verified-Plugins/WKWebView#108]
this should open a websql db, but instead causes an exception - easy to replicate, just type window.openDatabase('db'); into a console inspecting a cordova app built with the plugin.

(otherwise this plugin is the most amazing thing ever, thank you!)

**Comment by EddyVerbruggen** [comment]
Hi, it seems to be an issue with WKWebView itself, not related to the plugin: https://bugs.webkit.org/show_bug.cgi?id=137760

Please keep an eye on that issue. Comment, vote, etc.
