### ISSUE TITLE
cordova-plugin-screenorientation-for-wkwebview doesn't respond to touch after rotation

### ISSUE THREAD

**Issue by davyboyhayes** [Telerik-Verified-Plugins/WKWebView#115]
In our app, we use the screen orientation plugin, so after using the WBWebView, I came across the #93 issue which suggests to use https://github.com/EddyVerbruggen/cordova-plugin-screenorientation-for-wkwebview.

I can see that the view is now rotated, but I am no longer getting responses to touchevents:

For example:

$('body').on('touchend', function(){console.log('touched');});

then touch the screen it's fine.

screen.lockOrientation('portrait');

No more events are being triggered.

**Comment by davyboyhayes** [comment]
Restarting the app, and doing the same:

$('body').on('touchend', function(){console.log('touched');});
screen.unlockOrientation();

Also shows this problem.

**Comment by davyboyhayes** [comment]
Using the standard plugin doesn't suffer this problem, but of course rotation is not working (rotates, then rotates back)

**Comment by davyboyhayes** [comment]
https://github.com/EddyVerbruggen/cordova-plugin-screenorientation-for-wkwebview/pull/1
https://github.com/EddyVerbruggen/cordova-plugin-screenorientation-for-wkwebview/pull/2

**Comment by EddyVerbruggen** [comment]
Merged those. If you need me to tag and publish that plugin anywhere just let me know.

**Comment by davyboyhayes** [comment]
It's your forked plugin... do with this as you will ;)
