### ISSUE TITLE
incompatable with CameraPreview plugin

### ISSUE THREAD

**Issue by austinhallock** [Telerik-Verified-Plugins/WKWebView#116]
https://github.com/mbppower/CordovaCameraPreview

The camera doesn't show up. It should be added behind the webview (with a transparent background). Works without the wkwebview plugin, and doesn't work with it (camera doesn't show up).

You can replicate it with the example app: https://github.com/mbppower/CordovaCameraPreviewApp

**Comment by EddyVerbruggen** [comment]
Hey @austinhallock I just deployed that app (pretty sweet app/plugin btw!) to my iPhone 6 with the latest WkWebView plugin installed.

I think you're using a pre 0.3.8 version of the plugin because since then we enabled transparancy on the webview. can you confirm this plz?
