### ISSUE TITLE
XDK build fails

### ISSUE THREAD

**Issue by giorgiobeggiora** [Telerik-Verified-Plugins/WKWebView#119]
Good morning,

i'm following this guide https://software.intel.com/en-us/xdk/docs/building-cordova-ios-app-with-wkwebview to use WKWebView but the build fails :( what's wrong?

![thebuildfailed](https://cloud.githubusercontent.com/assets/9007227/8307789/d868702e-19c0-11e5-95e5-7ea925116801.png)

I'm using XDK and Cordova latest versions (the version in the screenshot refers to old versions because i tried older versions too and the result is the same)

Thanks.

**Comment by EddyVerbruggen** [comment]
Please direct your question at the kind folks of the Intel XDK because that's not something we can investigate as it's an error on their platform of which we don't have access to things like app configuration and logfiles.
