### ISSUE TITLE
Failed to install 'com.telerik.plugins.wkwebview'

### ISSUE THREAD

**Issue by bentaly** [Telerik-Verified-Plugins/WKWebView#121]
When I run: 

cordova plugin add com.telerik.plugins.wkwebview

I get the following error:

Failed to install 'com.telerik.plugins.wkwebview':Error: 404 Not Found: cordova-plugin-webserver

Do you know why this is?

I know you said this wont be needed when "Apple releases a fixed WKWebView" but I need my app to be backwards compatible. 

Either way, an answer would be greatly appreciated.

(Great work on this and your other plugins - by the way)

**Comment by EddyVerbruggen** [comment]
Are you using the Cordova CLI? If so, which version of Cordova are you on (`cordova --version`)? If it's less than 5, please update (`[sudo] npm install -g cordova`) and try again.

**Comment by bentaly** [comment]
That solved it for me! thanks

**Comment by EddyVerbruggen** [comment]
:+1:

**Comment by uzumakinaruto123** [comment]
@EddyVerbruggen  i am getting the same error ! on latest cordova version 6.0.0 !

if i add it with `cordova plugin add https://github.com/Telerik-Verified-Plugins/WKWebView`

it works but then ios build fails with following error :- 

`CompileC build/Crosswalk\ TestApp.build/Debug-iphonesimulator/Crosswalk\ TestApp.build/Objects-normal/i386/MyMainViewController.o Crosswalk\ TestApp/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

help is appreciated !

**Comment by EddyVerbruggen** [comment]
That's cordova-ios-4, right? It's not (currently) supported by this plugin. Cordova-iOS 3.x is.

**Comment by uzumakinaruto123** [comment]
Thanks alot for the reply ! do you recommend going back to cordova-ios-3 ? or should wait for the update ! any alternative plugin ?

**Comment by EddyVerbruggen** [comment]
Check this: https://github.com/Telerik-Verified-Plugins/WKWebView/issues/209

**Comment by uzumakinaruto123** [comment]
thanks ! :) will check :+1:
