### ISSUE TITLE
Plugin not getting installed

### ISSUE THREAD

**Issue by piyushkhare11** [Telerik-Verified-Plugins/WKWebView#125]
I am using Cordova 3.5 but when I am trying to install the plugin using CLI command its giving following issue:

cordova plugin add com.telerik.plugins.wkwebview
Fetching plugin "com.telerik.plugins.wkwebview" via plugin registry
Installing "com.telerik.plugins.wkwebview" for ios
Fetching plugin "cordova-plugin-webserver" via plugin registry
Failed to install 'com.telerik.plugins.wkwebview':Error: Failed to fetch package information for cordova-plugin-webserver

Will be great to know some suggestion if I am doing something wrong.

Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Hi, see #121. I'll leave this one open for future reference.

**Comment by ammubasha** [comment]
cordova-plugin-webserver can be installed separately? if so from where can i get this plugin?.

**Comment by EddyVerbruggen** [comment]
It's on npm. If you're using the latest cordova cli it should work without hassle.

**Comment by ammubasha** [comment]
In latest cordova5.0 if i build and install the app using phonegap command the application didn't open in ios 8. hope phonegap is wrapper over cordova and it should work.
