### ISSUE TITLE
statusbar overlway webview regression issue

### ISSUE THREAD

**Issue by northkode** [Telerik-Verified-Plugins/WKWebView#128]
looks like the status bar plugin is no longer working with this build. 
I set overlayWebView(false) and it does nothing the status bar is over top of my content.

Thanks

**Comment by EddyVerbruggen** [comment]
Which version do you use? And does it make a difference when using the latest release version vs the master branch? If so, I have an idea where to look..

**Comment by northkode** [comment]
How do i go about installing a different version? plugins add pluginname@version? i always just follow the plugin package name for install

**Comment by mn-martin** [comment]
I'm having the same problem using following plugins:

````
    <!-- StatusBar -->
    <gap:plugin name="com.phonegap.plugin.statusbar" />
    <preference name="StatusBarOverlaysWebView" value="true" />

    <!-- WKWebView Polyfill -->
    <gap:plugin name="com.telerik.plugins.wkwebview" />
````

I'm working with Adobe PhoneGap Build if it helps.

**Comment by mn-martin** [comment]
Using following Plugin Reference instantly fixed it for me:

````
<gap:plugin name="com.telerik.plugins.wkwebview" source="plugins.cordova.io" />
````

**Comment by EddyVerbruggen** [comment]
@mn-martin that's indeed a newer version than without the `source` param. :+1:
