### ISSUE TITLE
Error on app startup

### ISSUE THREAD

**Issue by standup75** [Telerik-Verified-Plugins/WKWebView#129]
Here is my list of plugins:

    "com.telerik.plugins.wkwebview"
    "nl.x-services.plugins.socialsharing"
    "https://github.com/danwilson/google-analytics-plugin.git"
    "cordova-plugin-inappbrowser"
    "cordova-plugin-file"
    "cordova-plugin-device"
    "cordova-plugin-file-transfer"
    "cordova-plugin-network-information"
    "cordova-plugin-whitelist"
    "cordova-plugin-splashscreen"

Here is a the error that I get:

    [Error] TypeError: undefined is not a constructor (evaluating 'new CustomEvent(eventName)')
      nativeEvalAndFetch (cordova.js, line 1114)
      nativeCallback (cordova.js, line 1100)
      global code (index.html, line 1)

Here is the content of commandQueue (don't know if that helps, but that's where I got lost in my investigation):

    "[["Device1693215739","Device","getDeviceInfo",[]],["File1693215740","File","requestAllPaths",[]],["NetworkStatus1693215741","NetworkStatus","getConnectionInfo",[]]]"

I would love for this to work, my app could really use the performance boost.

Any pointer?

**Comment by standup75** [comment]
Ok, so removing these plugins seem to get rid of the error:

    "cordova-plugin-file"
    "cordova-plugin-device"
    "cordova-plugin-file-transfer"

 but my app, that works without this plugin does not work without.
My app uses angular 1.4.2, has this been tested with angular at all?

**Comment by revolunet** [comment]
looks like you need a polyfill for `CustomEvent` on Safari : https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

not related to angular
