### ISSUE TITLE
Incompatible with iOS9 Public Beta 1

### ISSUE THREAD

**Issue by nitzanwilnai** [Telerik-Verified-Plugins/WKWebView#131]
It appears this plugin is incompatible with iOS9 Public Beta 1. 

I created a brand new project, loaded all my plugins except this one and it ran fine. 

Once I add this plugin, it crashes in main.m on:
        int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");
with EXEC_BAD_ACCESS.

Note that if you compile it on iOS 8.4, then update to iOS 9, the app will run fine. It is only when it is compiled from scratch using XCode 7 Beta 3 that it crashes. 

Also, if you delete the iOS 9 Beta profile, you can install the app to it using XCode 6, but it will still crash.

**Comment by shepsii** [comment]
getting the same thing here...

**Comment by nitzanwilnai** [comment]
Still happening on public beta 2.

**Comment by clauderic** [comment]
ditto

**Comment by EddyVerbruggen** [comment]
Hi, I waited a bit to see if Apple would change things again, perhaps even for the better, but with the latest beta this plugin was still broken. So I assume it will be with the final release.

I just released 0.5.0 of this plugin which should be compatible with iOS9. I kindly ask you to test it a bit and report back here.

Thanks guys,
Eddy

**Comment by clauderic** [comment]
@EddyVerbruggen Works great so far!

**Comment by nitzanwilnai** [comment]
How do I install version 0.5.0?

cordova plugin add com.telerik.plugins.wkwebview gives me version 0.4.0:
com.telerik.plugins.wkwebview 0.4.0 "WKWebView Polyfill"

**Comment by shepsii** [comment]
cordova plugin add com.telerik.plugins.wkwebview@0.5.0 would be the usual
cordova command line format for this, but I haven't personally tried it yet!

**Comment by EddyVerbruggen** [comment]
It wasn't released to the registry yet - it is now!

**Comment by shepsii** [comment]
Hi Eddy, bit confused here. When I update to the newest version of plugin my "cordova build ios --release" fails. It says "You may not have the required environment or OS to build this project". I do have the Xcode beta installed and updated; when I remove the wkwebview plugin the compile runs. Am I missing something?

And just to clarify: If we compile a project with 0.4.x, and then release through Xcode 6, that'll be fine; therefore the reason for this fix is more to deal with app submission when Apple insist that apps are built with Xcode 7 (as they tend to do each Jan/Feb)

Thanks!
Simon

**Comment by shepsii** [comment]
Scratch that. usual cordova platform remove ios; cordova platform add ios; cordova build .... voodoo sorted this!

**Comment by LukePulverenti** [comment]
what about rendering images using file:// url's? is that something we should be able to do now?

**Comment by EddyVerbruggen** [comment]
@LukePulverenti I would think so, yes.
