### ISSUE TITLE
WKWebview crash recovery weirdness

### ISSUE THREAD

**Issue by martinlingstuyl** [Telerik-Verified-Plugins/WKWebView#133]
Hi guys,

If my app crashes the WKWebview, it restarts just fine, as promised. 

The only problem is that is has forgotten all things in local storage. This would seem logical, but then I manually close the app and restart it cold, and hey... it will show the lost items from local storage again, like nothing has changed.

Weird huh! 
Also, (and maybe this is related) when I open Safari on my mac to use the Safari debugger and go to the submenu for my device (on the 'developer' tab) it will show localhost:12344/ as one of two items I can Debug. the other being a blank item. After a WKWebview crash it will show two blank items + localhost:12344.
Maybe somehow a second UIWebview is instantiated or something? I don't know how this works below the hood. I'm just describing.

Anyway, maybe a solution for me would be to have an alternate crashrecovery option in the config.xml that will close the app entirely instead of restart the wkwebview. That would be acceptable behavior for me.

**Comment by EddyVerbruggen** [comment]
It seems like LS locations may have been changed recently in iOS, so I'm thinking it's best to offer an option to disable LS as a whole. For new apps it's best to set the new `config.xml` `DisableLocalStorageSyncWithUIWebView` property to `true`, for existing apps where you want users to have their LS migrated you can test with the default settings. Still, if you run into trouble I'd advice you to also set the property to `true`.

Note that if it's `false` (the default, and the same as it was before) LS will be copied back and forth between WK and UI webview every time the app starts/stops. Which I added as a nice feature to be able to downgrade in case of trouble, but it may not be as bulletproof as I hoped.

Available in 0.5.1.

**Comment by martinlingstuyl** [comment]
Hi Eddy,

So just to verify: You're saying to disable LS as a whole, but you probably only mean disabling the sync, seeing the title of the property. That right?

So the expected behavior once I set the property, is that when the app crashes and restarts, the local storage will be loaded from WKWebview again? (or does LS not persist on WKWebview at all?)

**Comment by EddyVerbruggen** [comment]
@martinlingstuyl My comment was ambiguous at best, I've updated it - you can disable the LS sync between uiwebview and wkwebview, not LS itself.

If you set the property to false, LS will never be copied at all.

**Comment by martinlingstuyl** [comment]
Ok, but what does that mean in practice: If my wkwebview crashes and reboots, the saved LS items will reappear? (or will it still be flushed)

**Comment by EddyVerbruggen** [comment]
If it crashes it will simply pick up where it left off - no copy is done, so anything in wkwebview's LS is kept.

**Comment by martinlingstuyl** [comment]
Ok, great, thanks
