### ISSUE TITLE
Determining whether device is using WKWebView or UIWebView

### ISSUE THREAD

**Issue by jason-engage** [Telerik-Verified-Plugins/WKWebView#136]
Is there a simple method for determining whether the ios device is using WKWEBVIEW vs. UIWEBVIEW?

I know that checking for window.indexedDB works, but it seems a bit of a hack. Maybe UIWEBVIEW is upgraded to support indexedDB sometime in the future, which breaks that verification method.

If no other method exists, can one be included in the next build?

**Comment by EddyVerbruggen** [comment]
If the plugin is added to your project you should have an object called [window.wkwebview](https://github.com/Telerik-Verified-Plugins/WKWebView/blob/master/plugin.xml#L30).

Hope that helps,
Eddy
