### ISSUE TITLE
Can't seem to get Access rules/CORS config right

### ISSUE THREAD

**Issue by adamgins** [Telerik-Verified-Plugins/WKWebView#137]
Hi, this package seems to make things superfast, thanks!!! 

I am running on Meteor and  hitting the following issue:

```
2015-08-02 10:20:46.165 Buzzy[92054:21905813] ERROR: Error: "Queue" network [undefined], errorClass@http://localhost:12344/packages/meteor.js?4dc9757b244a30bdf37a732ac4db4026ce56fb6b:558:24
http://localhost:12344/packages/cfs_upload-http.js?cf37b2941c8cdbfd85cdc3948f57fed4bb429081:379:32
```
See 
https://github.com/practicalmeteor/meteor-wkwebview/issues/6 & 
https://forums.meteor.com/t/ios-wkwebview-origin-http-localhost-12344-is-not-allowed-by-access-control-allow-origin/7545

I see the documentation mentioning:

```
The worst issue is that WKWebView doesn't allow loading files from the file (file://) protocol like UIWebView does. This is what Cordova uses internally to load files from the www folder. Using an embedded local http server to load the www folder from the http protocol circumvents this issue.
```

I have tried various meteor settings like `App.accessRule('http://localhost:12344/* ');` and `   BrowserPolicy.content.allowConnectOrigin("localhost:12344");` , `  BrowserPolicy.content.allowOriginForAll("localhost:12344");` and even tried using `*` but I can't seem to work out the issue. 

Any help appreciated,please?

**Comment by EddyVerbruggen** [comment]
This is more of a Meteor question really, which I'm not really familiar with. There seems to be a similar question [here](https://github.com/meteor/meteor/issues/4132) which has a possible working solution as well.
