### ISSUE TITLE
Integrating with Meteor + Ionic

### ISSUE THREAD

**Issue by woniesong92** [Telerik-Verified-Plugins/WKWebView#139]
I am building an iOS app with Meteor and Ionic (Meteoric), and I am having troubles with the keyboard behavior on my app. I would really appreciate it if you could take a look at it. I am also referring to #27 

Here's what's happening:
https://www.youtube.com/watch?v=McBuwu5Ef78

I forked Meteoric and modified [ionKeyboard.js](https://github.com/woniesong92/meteor-ionic/blob/master/components/ionKeyboard/ionKeyboard.js) file. Basically, I removed all the scrolling behavior except for adding `bottom:` to keyboard-attached elements and scrolling to top whenever a keyboard appears. As you can see in the video, the behavior (scrolling down and up for the first 200ms) is not as desired although the final position of keyboard is okay.

I am currently relying on this [wrapper](https://github.com/practicalmeteor/meteor-wkwebview) to install wkwebview into my meteor app. It's possible that the newest version of Telerik keyboard has not been merged into that library, and that's why I am having all these problems. I am not sure if the nature of the problems described in #27 is the same as mine.

If you could provide some insight on this matter, it would be very helpful to all the Meteor users who want to install WKWebview into their mobile apps and have to give up because of the keyboard problems.

**Comment by kaansoral** [comment]
(off topic) keyboard and inputs are the most challenging aspect of html/webkit development, I only use dialogs for text inputs on android for example, otherwise the keyboard input routines definitely fail on a subset of devices, no matter what you do

I think a decent text-input plugin would be the ultimate solution to these problems, it's not as optimal as a native keyboard, but considering the native routines almost never work right, it would be a simple solution (the dialog/prompt works too, but it's not pleasing) - again I'm aware this is not exactly on-topic

**Comment by EddyVerbruggen** [comment]
Agree with @kaansoral that it's offtopic (haha) and that keyboard input is a pain in the a** (especially on Android).

@woniesong92 You're right, that fork is lacking the (very) recent adjustments for the keyboard. It's hard to advice anything else than having that updated first before chasing (potentially) the same problem again.

**Comment by woniesong92** [comment]
@EddyVerbruggen Please allow me to ask you one more question. The issue I am having right now is when you have an input field at the bottom of the screen, if you click (touch) it, the keyboard will open and the entire screen will scroll down. It seems like a behavior that `cordova.plugins.Keyboard.disableScroll(true);` should prevent. Am I correct? If so, did you have to solve this problem in a recent commit?

**Comment by woniesong92** [comment]
Sovled with https://github.com/Telerik-Verified-Plugins/WKWebView/issues/27
