### ISSUE TITLE
Getting NSURLErrorDomain error -999 in IAB which isn't thrown when using old viewer

### ISSUE THREAD

**Issue by dgerding** [Telerik-Verified-Plugins/WKWebView#146]
Hi,
I'm getting 'NSURLErrorDomain error -999' which I think (a bit hard to trace) near an $AJAX post.  I'm posting to Telerik backend.  Not sure what cors related (?) header info I would use in that context... assuming that that's the problem.

**Comment by mobiledev2017** [comment]
I am facing similar issue where all AJAX request with localfile load are failing due to CORS or NULL Origin issue. Any idea what can be done to resolve the issues?
I have tried adding the headers and that did not solve the problem.

**Comment by EddyVerbruggen** [comment]
In case you were on 0.5.0, please try 0.6.0+. Reopen this issue in case you still have trouble.
