### ISSUE TITLE
GCDWebserver version used in wkwebview

### ISSUE THREAD

**Issue by srksista** [Telerik-Verified-Plugins/WKWebView#148]
In wkWebView, which version of GCDWebServer framework is used. How can I get the version of GCDWebServer used in wkWebView.

I have already checked Info,plist in GCDWebServer framework but didn't find any variable in GCDWebServer to get Version.

**Comment by EddyVerbruggen** [comment]
It should be this one: https://github.com/swisspol/GCDWebServer/tree/00b2c38109871dee91ffa6a58919cd3ccae8d034

**Comment by srksista** [comment]
Thanks for the reply.

But, when I tried to download the source of wkwebview for version 0.3.7 from releases. 
After I unzip the source code and directory path WKWebView-0.3.7/src/ios we have GCDWebServer.framwork. 

I need to know the GCDWebserver Version used in the WKWebView-0.3.7 source.

**Comment by EddyVerbruggen** [comment]
Aha, 0.3.7 used a bundled GCDWebserver, later releases use the one referenced in the link above.

It was added by PR in #43 during last December so you may need to ask the submitter which exact version was used back then, but I'm guessing v 3.2.1.

**Comment by srksista** [comment]
Thank you
