### ISSUE TITLE
Ajax requests , angular partial loads not working with localfilesystem in iOS9

### ISSUE THREAD

**Issue by mobiledev2017** [Telerik-Verified-Plugins/WKWebView#149]
Ajax requests , angular partial loads not working with localfilesystem in iOS9 0.5 version plugin.
Error "Origin with Null is not supported" or "Cross Dmoain Request not supported"

**Comment by mobiledev2017** [comment]
Hi Eddy, Any thoughts?

**Comment by EddyVerbruggen** [comment]
Do you have a simple testapp for me?

**Comment by mobiledev2017** [comment]
I do not have it ready but  will create one and upload later today.

**Comment by srksista** [comment]
mobiledev2017: using different login to post this. Please find the sample code and screen of error displayed in safari.

Sample Code: https://github.com/srksista/Sample
![screen shot](https://cloud.githubusercontent.com/assets/431970/9750177/1a34f542-565a-11e5-8f74-4b5b66b2a0be.png)

**Comment by mobiledev2017** [comment]
Hi Eddy, Did you get a chance to look at the app?

**Comment by EddyVerbruggen** [comment]
Hi, I've played with it and reproduced the error.

Basically ajax-loading files from the file:// protocol is not possible because in wkwebview even these local requests must adhere to CORS restrictions, so they need to come from http.

I'm afraid this means we still need the embedded webserver.

**Comment by jreiter** [comment]
Hey Eddy, any idea when there might be a new build for iOS 9 that uses the embedded webserver?  I tried both 0.4 and 0.5 on iOS 9, and both are giving me issues

**Comment by EddyVerbruggen** [comment]
Working on it! Hoping to solve this later today.

**Comment by EddyVerbruggen** [comment]
@jreiter can you elaborate on your issues please? Perhaps a testapp showing the issues.

**Comment by jreiter** [comment]
I can see if I can come up with a test app.  Right now, I'm having issues getting 0.5 to load the app much at all on iOS 9; just getting a blank white screen at launch, and it doesn't seem to be finding index.html.  Works with no issues on iOS 8.

**Comment by EddyVerbruggen** [comment]
OK, thanks, I'll see if I can reproduce the white screen.

**Comment by EddyVerbruggen** [comment]
Getting real close, I hope you're available to give the new version a spin once it lands.

**Comment by EddyVerbruggen** [comment]
@jreiter @mobiledev2017 @srksista please test the master branch for any issues. It's kinda urgent with iOS9 around the corner, so I'd like to officially release this today.

**Comment by jreiter** [comment]
I've tried it out with my application, and the blank white page is no longer a problem!  I am having CORS issues when the app makes AJAX requests, however:

Origin http://localhost:12344 is not allowed by Access-Control-Allow-Origin

I can experiment with changing the Access-Control-Allow-Origin on my servers to '*' temporarily, but it there a recommended way to handle this?

**Comment by EddyVerbruggen** [comment]
Awesome, that's what I like to hear!

That CORS restriction has been in effect since the first version of this plugin since WKWebView itself enforces it. Indeed you need to whitelist localhost:12344 or *. All apps, native and hybrid must respect CORS according to Apple. Not a bad thing but it may be a pain in the *** for folks not having control over the remote server.

**Comment by jreiter** [comment]
Yep, no problems after adding the necessary CORS headers to the server.  Thanks!

**Comment by srksista** [comment]
Thanks Eddy,able to using localhost.

**Comment by rayshan** [comment]
Does this new flag help with not having to spin up a local server?

`[WKWebView loadFileURL:allowingReadAccessToURL:]`

Found it in this thread: http://stackoverflow.com/questions/24882834/wkwebview-not-loading-local-files-under-ios-8

**Comment by EddyVerbruggen** [comment]
@rayshan That would mean the page is loaded from the `file://` protocol which will mean you'll run into trouble when communicating with a remote webserver because CORS restrictions only allow http clients. So no.

**Comment by rayshan** [comment]
Got it, thanks @EddyVerbruggen.
