### ISSUE TITLE
jQuery ajax calls: Origin null is not allowed by Access-Control-Allow-Origin.  

### ISSUE THREAD

**Issue by codeconsole** [Telerik-Verified-Plugins/WKWebView#15]
I can't make any jQuery ajax calls after installing the plugin.

All ajax calls now result with an error "Origin null is not allowed by Access-Control-Allow-Origin. "

even if I add <access origin="*" /> to the config.xml

**Comment by ryd0rz** [comment]
Unfortunately I am having the same issue when using telerik. I am getting 405 not permitted on the preflight options request. I am sending to a cbLite database on the same device. The cbLite doesn't support the options header.

Is there a way to turn off the preflight on your telerik app, if not i'll have to uninstall?
