### ISSUE TITLE
Conflict between apps

### ISSUE THREAD

**Issue by afkpost** [Telerik-Verified-Plugins/WKWebView#150]
We have two apps. It seems like there is some caching between the apps. A simple way to recreate issue:

* Create app A with "Welcome to App A" as only content (no JS or CSS)
* Create app B with "Welcome to App B" as only content (no JS or CSS)
* Install both apps and clear them from memory
* Start App A: Welcome to App A is shown - great
* Start App B: Welcome to App A is shown - wtf?

We can change our file names, but that does not seem as a good solution, since an "evil" app quite easy would be able to inject code into our app.

**Comment by afkpost** [comment]
Furthermore cordova.js is caches, so App A tries to load App B's plugins

**Comment by EddyVerbruggen** [comment]
Hi, AFAIK that can only happen if you use the same app id for both apps. Am I correct?

**Comment by afkpost** [comment]
Nope. App A: com.compellingsoftware.a and App B: com.compellingsoftware.b

I do not think you are allowed to install two apps with same id...

**Comment by EddyVerbruggen** [comment]
Correct, it would simply overwrite the first app but you may see data of the first one in the second. I was not yet able to reproduce this when both apps have a distinct app id...

**Comment by afkpost** [comment]
I have attached a screen shot of the screen. This is from the simulator (iOS 8.4), but same issue arises on a psychical device (iPhone 5, iOS 9.0 beta). Code can be found [here](https://dl.dropboxusercontent.com/u/6298530/conflicting_apps.zip)

![ios simulator screen shot 08 sep 2015 10 11 10](https://cloud.githubusercontent.com/assets/2212109/9729764/047dedaa-5612-11e5-9f88-c05cc3499073.png)

**Comment by EddyVerbruggen** [comment]
Check [this](https://dl.dropboxusercontent.com/u/10061342/wkwebview-appconflict.mov) out. You app installed on my iPhone6 running iOS 8.4.1. All looks fine. I'm lost...

**Comment by revolunet** [comment]
can you check which ports are used on both app ? you can see it in xcode console or safari debugger

**Comment by afkpost** [comment]
Both uses port 12344

**Comment by revolunet** [comment]
ok... maybe then the first server is not killed and app B use app A server ?

**Comment by afkpost** [comment]
I think it is something to do with caching. When I in the console refreshes the app, it sometimes loads the right app.

In the broken app (App B) I have tried to request index.html and index.html?foo.  
index.html gave me "Welcome to App A" - bad  
index.html?foo gave me "Welcome to App B"

Both have a cache-control header with a max-age of 60, so it seems caching could be the problem...

**Comment by EddyVerbruggen** [comment]
@afkpost Interesting case - where did you set the cache control header?

**Comment by afkpost** [comment]
I did not set any header. I have tried to change the line cacheAge:60 to cacheAge:0 in AppDelegate+WKWebviewPolyFill.m - but it did not work, although the new cache control header is not "no-cache".

**Comment by afkpost** [comment]
Have you looked more into this issue?

**Comment by manu3569** [comment]
I encountered the same issue. The first attempt at a fix was to check if the port was in use by trying to bind/listen to it. A failure to bind would indicate that the port is in use. Repeat until an unused port is found. In practice this didn't work. Maybe because of some kind of sandboxing between apps.

An alternate, though not best, solution would be to randomize the port every time the server starts in `AppDelegate+WKWebViewPolyfill.m`. This fix has worked thus far.

```
    int lowerBound = 49152;
    int upperBound = 65535;
    int httpPort = lowerBound + arc4random() % (upperBound - lowerBound);
```

**Comment by revolunet** [comment]
it would be nice to remember that random port because if you change the port randomly, you wont be able to restore the app localStorage (tied to url+port)

**Comment by EddyVerbruggen** [comment]
That's right. It's a bit frustrating they thought that would be a good naming scheme for the LS file.

**Comment by manu3569** [comment]
Maybe a better solution would be a configurable port number. That would keep it consistent, and every app can get a different port.

**Comment by EddyVerbruggen** [comment]
@manu3569 not a bad idea, but it's a bit of an advanced feature so perhaps an optional property in config.xml would be a good fit?

**Comment by manu3569** [comment]
I like that idea. Also, if that config option is missing, it can always default back to `12344`, to ensure backwards compatibility.

**Comment by revolunet** [comment]
awesome :+1:

**Comment by EddyVerbruggen** [comment]
Guys, you can now try this feature. See the changelog in the readme for 0.6.3. I will tag the release in a few days.

**Comment by afkpost** [comment]
It works as expected :-) a release on npmjs.org would be nice ;-)

**Comment by EddyVerbruggen** [comment]
Great, thanks for checking that. Go grab it here: https://www.npmjs.com/package/cordova-plugin-wkwebview

**Comment by revolunet** [comment]
Thanks ! :+1:
