### ISSUE TITLE
alert/confirm/prompt() is not working

### ISSUE THREAD

**Issue by speigg** [Telerik-Verified-Plugins/WKWebView#152]
The callbacks in CDVWebViewUIDelegate are not being called when I execute `alert()` (in any frame). Likewise with `confirm` and `prompt`. Using version `0.5.1`.

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this! They work now. Will release a 0.5.2 later today, but it's available on master right away.

**Comment by luthian** [comment]
Is this still working?

I'm using PhoneGap Build to make the app and running on iOS 9.x; if I use a Development cert, alerts work and I can debug using Safari. If I use a Distribution cert (e.g. the version in the app store), alerts silently fail and I cannot debug in Safari.

I haven't tested with a beta profile or ad-hoc distribution cert. The app is CarGurus if that helps.

Am I missing something here? Is there something I need to do to enable alerts()?
