### ISSUE TITLE
Add "/tmp" to supported paths

### ISSUE THREAD

**Issue by rajatrocks** [Telerik-Verified-Plugins/WKWebView#155]
The Cordova Camera plugin drops its files into the "/tmp" folder. Adding that path to the existing "/Documents" and "/Library" paths would enable app developers to access the local images for previews. See details here: https://github.com/Telerik-Verified-Plugins/WKWebView/issues/81

**Comment by EddyVerbruggen** [comment]
Great idea, i'll test if it doesn't break anything and include it in 0.6.1.

**Comment by rajatrocks** [comment]
Thanks @EddyVerbruggen!
