### ISSUE TITLE
XMLHttpRequest Exception 101 ios9

### ISSUE THREAD

**Issue by jason-engage** [Telerik-Verified-Plugins/WKWebView#159]
The network_err problem seems to be back when running from xcode 7 on ios9.1 simulator. (Probably on the device too but haven't tried).

See details here:
https://github.com/Telerik-Verified-Plugins/WKWebView/issues/2

I'm running ionic as well. @mhartington

**Comment by EddyVerbruggen** [comment]
That depends, with 0.5.0 it's probably broken, but 0.6.0 should be fine - I just confirmed that in the iPhone 6s simulator.

Which plugin version are you using?

**Comment by jason-engage** [comment]
Ok, im using 0.5.0, didn't know there was a 0.6! Thanks Eddie, will update it now

**Comment by EddyVerbruggen** [comment]
Yeah, I released it last week because of issues with iOS9 GM :(
