### ISSUE TITLE
Latest version (0.6.0) missing in plugin repository

### ISSUE THREAD

**Issue by bjomi** [Telerik-Verified-Plugins/WKWebView#160]
Hi,

we're using your great plugin in our app and now we're experience issues in iOS 9 (of course). So I need to upgrade to 0.6.0. We're using Phonegap Build so the plugin needs to be in a repo that it supported by them. When looking I can find 0.5.0 here: http://plugins.cordova.io/#/package/com.telerik.plugins.wkwebview

But we would need 0.6.0. Would it be possible for you to make 0.6.0 available here? Or better yet, here: http://plugins.cordova.io/npm/index.html (where I can't find the plugin at all). As you can imagine time is of the essence here, so would very much appreciate if you would be able to do this for us.

Thanks for a great plugin. It has been a life saver for us.

Regards, 
Björn

**Comment by EddyVerbruggen** [comment]
Hi @bjomi,

That npm repo is not published by us unfortunately so we can't update that release.

And plugins.cordova.io is readonly these days :{

That being said, give me a few hours to come up with something.

**Comment by etiennea** [comment]
I published that one, I will update it now. Would be better if @EddyVerbruggen published to npm directly!

**Comment by chaosterx** [comment]
Hello, i just removed the wkwebview by mistake in attempt to update. But now i am getting a 404 not found :\ what happened? can someone help me! i am unable to build the project now due to this

**Comment by EddyVerbruggen** [comment]
@chaosterx which repo are you referring to?
@etiennea [Adding me as an owner](https://docs.npmjs.com/cli/owner) on [the npm project](https://www.npmjs.com/package/cordova-plugin-wkwebview) would suffice, thanks for responding!

**Comment by chaosterx** [comment]
com.telerik.plugins.wkwebview  - this repo isn't available

**Comment by EddyVerbruggen** [comment]
@chaosterx Was that on plugins.cordova.io?
You should be able to migrate to npm: cordova-plugin-wkwebview, in a short while the latest version will be up

**Comment by chaosterx** [comment]
alright that sounds great! its just a matter of time then? Kindly notify on this thread when its up so i can re-add as a plugin

**Comment by chaosterx** [comment]
I am sorry one more question, currently after i removed the plugin from my cordova Xcode project, there is another error that is occuring when building (ld: framework not found GCDWebServer
clang: error: linker command failed with exit code 1 (use -v to see invocation))

Is this related? Any idea?

**Comment by EddyVerbruggen** [comment]
That's likely to be fixed when the plugin is re-added from npm

**Comment by EddyVerbruggen** [comment]
0.6.0 is now available on npm: https://www.npmjs.com/package/cordova-plugin-wkwebview

`cordova plugin add cordova-plugin-wkwebview` should fetch it.

@etiennea thx for adding me. It's not perfect, with the github url pointing at your fork, and the readme doesn't seem to update, but at least folks can now use the latest version.

**Comment by chaosterx** [comment]
Thank you for the notification, i am still getting 404! Perhaps propagation delay?

i am getting this  "npm http 404 http://registry.cordova.io/cordova-plugin-wkwebview"

**Comment by bjomi** [comment]
Thank you so much for fast reply and swift actions!

**Comment by EddyVerbruggen** [comment]
@chaosterx How are you adding the plugin? If it's phonegap build, please use `source="npm"`

@bjomi you're welcome!

**Comment by chaosterx** [comment]
its a cordova project under Xcode and i am running the command "cordova plugin add cordova-plugin-wkwebview" from under the mac terminal. what am i doing wrong?

**Comment by EddyVerbruggen** [comment]
@chaosterx sound like you need to clean your local npm cache..

**Comment by chaosterx** [comment]
hmmm...i may need a little help with that, would you possibly guide me?

**Comment by EddyVerbruggen** [comment]
No worries: `npm cache clean cordova-plugin-wkwebview`

**Comment by chaosterx** [comment]
ok i ran that from the terminal, re-attemped the cordova plugin add command and still the same issue :\

perhaps ill restart the mac and check again

**Comment by EddyVerbruggen** [comment]
Perhaps clean again and try creating a new project first..

**Comment by chaosterx** [comment]
Maybe ill re-generate the iOS platform version and re-attempt that. What do you think?

**Comment by chaosterx** [comment]
Ok, what i did was update the NPM and the cordova version and it did fetch the version and install it so thank you for that. I am now getting the 

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_MyMainViewController", referenced from:
      objc-class-ref in AppDelegate+WKWebViewPolyfill.o
ld: symbol(s) not found for architecture i386

I recall something was added back with the older version of this plugin. Can you guide me?

**Comment by EddyVerbruggen** [comment]
@etiennea FYI I've now published the latest to https://www.npmjs.com/package/@telerik/cordova-plugin-wkwebview since we're planning to release our plugins to the `@telerik` scope anyway.

So the readme now advises folks to install with `cordova plugin add @telerik/cordova-plugin-wkwebview`

@chaosterx I think that's because of the mess you just had to go through. A likely fix is opening your platforms/ios/ project in XCode, selecting `MyMainViewController.m` (silly name, I know) on the left, and making sure your project is checked at 'Target Membership' on the right (see screenshot).

<img width="959" alt="screen shot 2015-09-17 at 19 40 00" src="https://cloud.githubusercontent.com/assets/1426370/9941112/7ef3eab8-5d73-11e5-9f3d-3e798a9faa2e.png">

**Comment by chaosterx** [comment]
Ok that error seems to have gone but others have appeared, i believe belonging to the same nature (e.g ReroutingUIWebView.m)

I have done the same for them but now i am getting this and i cannot find where to handle it

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_WKUserContentController", referenced from:
      objc-class-ref in MyMainViewController.o
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in MyMainViewController.o
  "_OBJC_CLASS_$_WKWebViewConfiguration", referenced from:
      objc-class-ref in MyMainViewController.o

**Comment by EddyVerbruggen** [comment]
Your project is so screwed - did you run `cordova prepare`? These are fixable by adding the `WebKit.framework` ;)

<img width="894" alt="screen shot 2015-09-17 at 19 48 22" src="https://cloud.githubusercontent.com/assets/1426370/9941304/acffff68-5d74-11e5-9a45-d4a20e593bb9.png">

**Comment by chaosterx** [comment]
Thanks a lot man! That was a nightmare to go through, and it isn't my code/project. I was handed this cuz the guy is on leave and i know a thing or two about cordova on mac ;) (NOT).

On any case, seems like i can build and start but i had a couple of questions regarding angular/polymer components. are they are still supported? Shadow dom etc... because the app contains that and i hope it can fall back gracefully

**Comment by EddyVerbruggen** [comment]
You're welcome. I don't see why those web techs would no longer work. If they did with the old version they should work with the new one. If not please open a new issue here, bu tmake sure it's related to this plugin. You can test without this plugin by (for example) opening `AppDelegate+WKWebViewPolyfill.m` and renaming `load` (line 19) to `blaaaah` (or anything by `load`, really).

**Comment by chaosterx** [comment]
Thank you so much, will do! :dancer:
