### ISSUE TITLE
Linker error with IOS 9 on device

### ISSUE THREAD

**Issue by jessiahr** [Telerik-Verified-Plugins/WKWebView#161]
I just updated to xcode 7 + ios9 and I can run this plugin in a fresh app no problem but when I run on device I get a linker error:

```
 'testx/Plugins/cordova-plugin-webserver/GCDWebServer.framework/GCDWebServer(GCDWebServerRequest.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

Is there something that I need to do to get this working with ios9?

**Comment by EddyVerbruggen** [comment]
Yeah, go into XCode and set `bitcode` to `NO` for the target (search for it in the 'Build Settings' tab).

**Comment by daviddahl** [comment]
On a related note, I tried to install 0.6.0 but it failed saying there was no candidate for 0.6.0:
Fetching from cordova plugins registry failed: No compatible version found: com.telerik.plugins.wkwebview@'>=0.6.0-0 <0.7.0-0'
Valid install targets:
["0.3.1","0.3.4","0.3.5","0.3.7","0.4.0","0.5.0"]

**Comment by jessiahr** [comment]
Setting bitcode to NO fixed the issue for me thank you!

**Comment by daviddahl** [comment]
yes, me too. thanks!

**Comment by iamsamwood** [comment]
Worked for me too, thank you !
