### ISSUE TITLE
 With Xcode 7 and iOS 9 my App hangs on splash screen.

### ISSUE THREAD

**Issue by saschaGit** [Telerik-Verified-Plugins/WKWebView#169]
Hi, I recompiled my App and now it's hanging after the splashscreen with spinner visible.
The App compiles after i have deactivate the bitcode setting. I have done updating teller.wkWebView Plugin to the newest version 0.6.1.
The last message in Xcode console shows "Started http daemon: http://192.168.0.23:12344/" but nothin else happen.
Have you any tips word ideas how to fix this.

**Comment by saschaGit** [comment]
I do some more investigation ion this issue and think that it's related to "IOS8.3 blank page #126".
Is their any news about this issue?

**Comment by EddyVerbruggen** [comment]
Hi @saschaGit I have to give you the same response as in #126 - can you send me a minimal project reproducing this error? I have not received one in #126 so far.

**Comment by saschaGit** [comment]
Hi Eddy, i have solved my issue. I think their was a problem with it when i have updated cordova and this plugin. I now have completely remove the plugin and newly add it. After that it works.
