### ISSUE TITLE
Trying to use tel: and mailto: hrefs

### ISSUE THREAD

**Issue by danbcooper** [Telerik-Verified-Plugins/WKWebView#170]
Thanks very much for this plugin.

I am trying to enable mailto: and tel: links in my app.  I've uncommented
createWebViewWithConfiguration in MyMainViewController .m and rebuilt.

I also see that a CDVWebViewUIDelegate is instantatiated and WKWebView * cordovaView.UIDelegate is set to this instance.  

However, I'm still not getting any navigation from the mailto: and tel: links.   I put
some logging output in the createWebViewWithConfiguration function to see if it is even being called, but I never see any output.

Should this functionality work?  

I'm using ionic 1.1.0 and xcode 7.0.1
com.telerik.plugin.wkwebview 0.6.0

**Comment by EddyVerbruggen** [comment]
Hi, you should be able to leave the native bits alone and do this:

```html
<a href="mailto:eddyverbruggen@gmail.com" target="_blank">mail!</a>
<a href="tel:+31611223344" target="_blank">call!</a>
```

I thought I added that to the readme but didn't.

**Comment by danbcooper** [comment]
Thanks Eddy!  Adding the target fixed it.

**Comment by EddyVerbruggen** [comment]
Awesome, time for me to update the readme :+1:
