### ISSUE TITLE
Doesn't copy to LocalStorage from UIWebView to WKWebView

### ISSUE THREAD

**Issue by gregavola** [Telerik-Verified-Plugins/WKWebView#177]
It appears that neither on Simulator (xcode 7), or Device (iOS 9.0.2) the UIWebView LocalStorage doesn't copy to the WKWebView, even with the workaround in the plugin init.

**Comment by EddyVerbruggen** [comment]
Hey Greg, should work again as I found the new naming scheme iOS uses for WKWebView's LS. It will be available in 0.6.2 when tagged, and in the master repo right now. I would love to have this tested a bit before tagging the new version.

Cheers,
Eddy
