### ISSUE TITLE
Config.xml with content of http://... fails to load.

### ISSUE THREAD

**Issue by fictorial** [Telerik-Verified-Plugins/WKWebView#186]
The issue is that the code is prepending file://...... blindly to the content element's src property and then assuming that it's a file-based URL.  I am using http://... for a ES2015 live reload workflow.

```
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 90000
    [self.wkWebView loadFileURL:URL allowingReadAccessToURL:URL];
#else
        NSURLRequest* appReq = [NSURLRequest requestWithURL:finalURL cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:20.0];
            [self.wkWebView loadRequest:appReq];
#endif
```

**Comment by EddyVerbruggen** [comment]
Are you able to send a PR fixing this issue?

**Comment by fictorial** [comment]
The code referenced in the top comment was outdated. I updated to master and fixed the issue. See the PR.

**Comment by fictorial** [comment]
The reason I want to load from a http-based URL is to enable live reload.

See [this stackoverflow question](http://stackoverflow.com/questions/33337602/how-can-i-use-es6-es2015-with-live-reloading-with-apache-cordova/33352695#33352695) for my solution.
