### ISSUE TITLE
Change to cordova-plugin-keyboard breaks hideFormAccessoryBar functionality when using WKWebView

### ISSUE THREAD

**Issue by rumit91** [Telerik-Verified-Plugins/WKWebView#187]
I have been relying on `cordova-plugin-keyboard` to hide the form accessory bar in iOS. However, [this change](https://github.com/cjpearson/cordova-plugin-keyboard/commit/9fc1f2f42c75764ecb2bd30399d5da8133d2a82f) broke the compatibility with WKWebView. 

Looks like with the previous code `cordova-plugin-keyboard` would attach observers to keyboard events and then look for the affected webview instance to apply the change to. Now the change is applied to the webview class and since WKWebView does not use that class the right property is not being modified. 

I tried changing `Class webBrowserClass = NSClassFromString(@"UIWebBrowserView");` to `Class webBrowserClass = self.webView.class;` to get the class of the instance, but that didn't work.

I also tried setting up the `inputAccessoryView` property in `ReroutingUIWebView.m` the same way `scrollView` is set up, but that didn't work either.

Any suggestions for how to fix this issue?

**Comment by Wenape** [comment]
This happens to me as well, haven't been able to fix it yet.

**Comment by andreialecu** [comment]
This seems to be a pretty big issue, any workarounds?

**Comment by berndartmueller** [comment]
+1

**Comment by andreialecu** [comment]
@berndartmueller this has been fixed in cordova-plugin-keyboard: https://github.com/cjpearson/cordova-plugin-keyboard/commit/33cbbd9c5b93ba5a1d4be8ff19f8fa8b5f76c2f0

If you use that one, it will work.

**Comment by berndartmueller** [comment]
@andreialecu: thank you!!

**Comment by fndppx** [comment]
App Store could reject?   if user this api
