### ISSUE TITLE
AllowInlineMediaPlayback Youtube IOS

### ISSUE THREAD

**Issue by jason-engage** [Telerik-Verified-Plugins/WKWebView#191]
Hi,

So I'm trying to get a youtube video using the iframe api (v3) to play Inline on ios.

I have set AllowInlineMediaPlayback to True in config.xml
I have set &playsinline=1 in the youtube url

If I remove WKWebView and go with UIWebView, the video will play inline. But when I add WKWebView it always goes to fullscreen when the video plays.

In the Youtube docs (https://developers.google.com/youtube/player_parameters?hl=en) - they have this to say:
"The definition of the playsinline parameter, which only affects HTML5 players on iOS, has been modified slightly. The definition now notes that setting the parameter value to 1 causes inline playback only for UIWebViews created with the allowsInlineMediaPlayback property set to TRUE."

It seems that they specifically mention UIWebView... is there a workaround or hack that will also make this work for WKWebView?

Thank you. 

ps. WKWebView rocks UIWebView! :)

**Comment by Nicolastriplec** [comment]
Same here, I can't put WKWebView on inline mode. I m using an UIWebView for now, but cpu and memory management are very poor. Waiting for a solution , thanks!

**Comment by epegzz** [comment]
I'd really need that as well :(

**Comment by EddyVerbruggen** [comment]
This is not really a plugin issue, rather WKWebView in general, so IMO this should be on SO to reach a broader audience.

The question is: can WKWebView play inline video like UIWebView can with the correct setting as mentioned in [this YouTube doc](https://developers.google.com/youtube/player_parameters?hl=en)?
