### ISSUE TITLE
deviceready doesn't fire

### ISSUE THREAD

**Issue by martatw** [Telerik-Verified-Plugins/WKWebView#194]
on ios 3.9.2

**Comment by EddyVerbruggen** [comment]
Can you please elaborate, because I think for most users it does. So on what device do you run this, did you include a reference to cordova.js, do you perhaps have a demo app that reproduces the issue?

Thanks for any input you can provide,
Eddy

**Comment by martatw** [comment]
Hi,

Sorry, my fault. My app (written with default UIWV) using WebSQL, whichis not supported on WKWebView. It was responsible for breaking down the app.
