### ISSUE TITLE
StatusBar Plugin Does not Work

### ISSUE THREAD

**Issue by lylepratt** [Telerik-Verified-Plugins/WKWebView#20]
The StatusBar Plugin does not appear to work. I'm assuming that the WKWebView is not respecting the Window resizing that the plugin does on the normal one.

**Comment by EddyVerbruggen** [comment]
Hi @lylepratt, 0.3.5 is fully compatible with the statusbar plugin. The only thing this last release added though was making sure the entire webview moves down a bit when the statusbar not overlapping the webview.

**Comment by jholt1** [comment]
I have just updated to 0.3.5 however The status bar is still overlapped. 

![screenshot 2015-01-20 20 11 47](https://cloud.githubusercontent.com/assets/7101754/5825136/0727a44c-a0e1-11e4-918e-ec8664db88be.png)
plugin: org.apache.cordova.statusbar 0.1.9 "StatusBar"

In the config.xml -

<feature name="StatusBar">
      <param name="ios-package" value="CDVStatusBar" onload="true" />
</feature>
<preference name="StatusBarOverlaysWebView" value="true" />
<preference name="StatusBarBackgroundColor" value="#00bcd4" />
<preference name="StatusBarStyle" value="lightcontent" />

**Comment by EddyVerbruggen** [comment]
@jholt1 That's the same effect you'd get without this plugin, right? `StatusBarOverlaysWebView = true` means the statusbar will bleed through the webview, setting it to `false` will make the webview move down.

If you're hacking in XCode, you can quickly confirm this by switching back to UIWebView by renaming `load` in `AppDelegate+WKWebViewPolyfill.m` to something else (like `dontload`).
