### ISSUE TITLE
file:// Not allowed and saved image not found (404)

### ISSUE THREAD

**Issue by Titoine** [Telerik-Verified-Plugins/WKWebView#201]
It seem the file:// doesn't work for me (Not allowed to load local resource). 

![Not allowed to load local resource](http://i64.tinypic.com/2ihrmzt.jpg)

And more, I can't load image frome Camera plugin witth File URI (404 not found)

![404 not found](http://i64.tinypic.com/vybgh0.jpg)

I thought It was functionnal now since 0.6.7. 
Without WKWebView , everything work great. 

Before that I was on WKWebView  0.4.0 and the file:// didn't work, so I used DATA_URL. But I could get back my image that I saved before (no 404).

WKWebView 0.6.7
Cordova 5.4.1

Thanks again for the great work :-)

**Comment by andreialecu** [comment]
You should be able to use an url like "http://localhost:12344/tmp/cdv_photo_007.jpg" in the first case, and   "http://localhost:12344/Library/NoCloud/....jpeg" in the second one.

**Comment by Titoine** [comment]
Getting 404 for both when replacing url. 
Does the simulator is for something ?

**Comment by Titoine** [comment]
Ok first case is second case and vice versa :)
Is there a proper way to edit these url ? 
Except testing that I'm on iOS so I have to replace the url.

**Comment by andreialecu** [comment]
Try something like `relativeUri = "/" + fileUri.replace(cordova.file.applicationStorageDirectory, '')` and set your src to that.

**Comment by Titoine** [comment]
Thanks a lot !
