### ISSUE TITLE
Missing Response Headers in GET request on http://localhost

### ISSUE THREAD

**Issue by Hydrog3n** [Telerik-Verified-Plugins/WKWebView#210]
Hello, Thanks for you plugin. 

In my projet I stream mp3 files from iphone storage. The webserver doesn't return the response header and i don't have a duration for my file, so i can't seek the audio track. 

To resolve this i changed this line : https://github.com/Telerik-Verified-Plugins/WKWebView/blob/master/src/ios/AppDelegate%2BWKWebViewPolyfill.m#L86 by 

```Objective-C
GCDWebServerResponse* response = [GCDWebServerFileResponse responseWithFile:fileLocation byteRange:request.byteRange];
[response setValue:@"bytes" forAdditionalHeader:@"Accept-Ranges"];
return response;
```
I post this issue as a fix to seek in mp3 file stored locally.

**Comment by EddyVerbruggen** [comment]
Hi,

If that doesn't break any other usage, do you feel like sending a PR for your change so others may benefit from it?

Thanks!

**Comment by Hydrog3n** [comment]
I don't know if it breaks any usage. I use only for this usage. It's why i post in issue.

**Comment by EddyVerbruggen** [comment]
No worries, thanks for posting the details here! - I hope it will be useful to others!

**Comment by Hydrog3n** [comment]
Do you want me to send a PR ?

**Comment by EddyVerbruggen** [comment]
Only if you time - I will test it with other usecases soon if you do.
