### ISSUE TITLE
what`s time ios 9 is work?

### ISSUE THREAD

**Issue by match08** [Telerik-Verified-Plugins/WKWebView#212]
what`s time ios 9 is work? ios 9 is not work now.

**Comment by EddyVerbruggen** [comment]
What do you mean exactly? This plugin has worked with iOS9 fine for a long time now.

The only thing it's not compatible with is cordova-ios-4 which was recently released. Ironically that release was mostly targeted at allowing other webviews than UIWebView, but it broke compatibility with this one in a serious way. Don't know when and if that will be fixed yet.
