### ISSUE TITLE
Cordova Camera not working

### ISSUE THREAD

**Issue by naviocean** [Telerik-Verified-Plugins/WKWebView#213]
Before added this plugins, my camera function works fine by using $cordovaCamera.getPicture()
But it doesnt work now.

**Comment by EddyVerbruggen** [comment]
Please elaborate. A little demo app reproducing this issue will help speeding up supporting you on this issue.

**Comment by naviocean** [comment]
@EddyVerbruggen, You can check with source at https://github.com/BharathiD/ionic-framework-tutorials/tree/master/CameraPluginDemo
This issue only occurs on iOS, but android works fine

**Comment by EddyVerbruggen** [comment]
Commenting out the line `popoverOptions: CameraPopoverOptions,` for both functions makes it all work nicely with the plugin. Don't know why, but let me know if that works for you too.

**Comment by naviocean** [comment]
@EddyVerbruggen it doesnt work even remove this line.
I tested on iphone 5s, 6 with ios 8.4 and ios 9.2

**Comment by EddyVerbruggen** [comment]
Did you try removing the app first? May help.

**Comment by naviocean** [comment]
I remove line "popoverOptions: CameraPopoverOptions" for both but not working.
I tried to remove WKWebView plugin and then app works fine again
Please check and help me to solve this issue

**Comment by EddyVerbruggen** [comment]
"Did you try removing the app first? May help."

**Comment by naviocean** [comment]
Hello,
I downloaded your link and everything work fine. Could you please tell all your step that you did?
Here is all my steps:
1.Clone source from https://github.com/BharathiD/ionic-framework-tutorials/tree/master/CameraPluginDemo
2. npm install
3. ionic platform add ios
4. ionic plugin add cordova-plugin-wkwebview
5. Using xcode to build on my iphone
What's wrong?

**Comment by naviocean** [comment]
Thanks, it works fine.
