### ISSUE TITLE
Can local resources be loaded from outside of www folder?

### ISSUE THREAD

**Issue by wideblue** [Telerik-Verified-Plugins/WKWebView#22]
This might be more of a question than an issue. I have application that first downloads some pictures and sounds and then presents them to a user.  The resources get stored in an application folder .../Data/Application/"some application ID"/Documents/NoCloud/ and in presentation view are linked to that location.  When running the application on simulator everything works ok but on device I get errors like this 
Failed to load resource
file:///var/mobile/Containers/Data/Application/"some application ID"/Documents/NoCloud/slike/olepvtum.png

I know there is a bug with accessing local resources with WKWebView and the workaroud was to add local web server to access them. Now I'm wandering if there is a problem with loading downloaded resources because they are not in www directory.  And if this is related to the local web serve, can this web server be configured to access also resources outside www folder.

**Comment by fenta23** [comment]
Any news on this?
Did someone tested it on iOS 8.1.3?

**Comment by clemenslermen** [comment]
Any news here? I'm caching files in: "file:///var/mobile/Containers/Data/Application/some_application/Documents/imgcache/" with imgcache.js and can't access them in WKWebview. Would be great to have a possibility to access them over the internal web server.

**Comment by micky2be** [comment]
Any news here?
Really need this to be fixed

**Comment by EddyVerbruggen** [comment]
@clemenslermen do you have a sample version of your app which I can reproduce the error with? An XCode project would be great. Same for @micky2be, if I can easily reproduce and debug your problem then I may be able to quickly fix it.

Thanks guys!

**Comment by micky2be** [comment]
Very similar issue than @clemenslermen
I'm trying to make the following app loader work
(https://github.com/markmarijnissen/cordova-app-loader)

**Comment by AkankS19** [comment]
Any solution this? my wkWebView version is 4.0.0
still i cant access my file from file system.

**Comment by EddyVerbruggen** [comment]
@AkankS19 it depends on where your files live. You can access files in /Library f.i.

**Comment by AkankS19** [comment]
@EddyVerbruggen i am downloading my file in persistent storage. In /Documents

**Comment by AkankS19** [comment]
I found one solution to this, in telerik WKWebView where i am downloading my file to  " file:///var/mobile/Containers/Data/Application/ApplicationID/Documents/filename.png".

I am using below path to access the file :-
 <img  src='/Documents/filename.png' > 
(As mention in Changelog 0.3.8 version of https://github.com/Telerik-Verified-Plugins/WKWebView).

It worked for me.

**Comment by SnehalJ1509** [comment]
@AkankS19 I was also facing the same problem. But now its fixed by your solution. Thanks!

**Comment by EddyVerbruggen** [comment]
Yeah, that's also mentioned [here](http://plugins.telerik.com/cordova/plugin/wkwebview), thanks for sharing guys!

**Comment by joshuachestang** [comment]
@AkankS19 Can you repost the path to access the file? The image is coming up as missing.

**Comment by schumannd** [comment]
Yes, I would like to see this path as well!
