### ISSUE TITLE
Variable(s) missing: WKWEBVIEW_SERVER_PORT

### ISSUE THREAD

**Issue by teo1310** [Telerik-Verified-Plugins/WKWebView#220]
Hi, 
Just beginning to play with cordova and plugins and managed to build some projects, but I am unable to correctly make the plugin work when:

```
cordova plugin add Telerik-Verified-Plugins/WKWebView --variable WKWEBVIEW_SERVER_PORT=12344
cordova platforms add iOS
```

First line : success
Second line : Failed to install 'com.telerik.plugins.wkwebview':Error: Variable(s) missing: WKWEBVIEW_SERVER_PORT

Cannot figure out why - can you help me ?
Many thanks.

**Comment by EddyVerbruggen** [comment]
Can nyou try it like this? https://www.npmjs.com/package/cordova-plugin-wkwebview#3-installation

**Comment by teo1310** [comment]
Thank you for the quick feedback.

I did that before but got :

**Comment by EddyVerbruggen** [comment]
Please update your cordova-cli to 5.x as that should work.
