### ISSUE TITLE
Don't start a new webserver after a crash if one is still running

### ISSUE THREAD

**Issue by EddyVerbruggen** [Telerik-Verified-Plugins/WKWebView#223]
I don't know if the webserver crashes as well after a webview crash, but if it doesn't a new webserver will be started on a different port. Since WKWebView ties LS to a port this means LS is lost during this session.

I'll add a guard to make sure if a webserver is still running it won't start a new one upon crash.

**Comment by devgeeks** [comment]
:+1:

**Comment by EddyVerbruggen** [comment]
Available in 0.6.9. Can't test it in case of a crash, but it works as expected when "simulating" it.
