### ISSUE TITLE
plugin network black screen

### ISSUE THREAD

**Issue by matrixreal** [Telerik-Verified-Plugins/WKWebView#225]
Hi,
i got black screen when add this plugin https://github.com/apache/cordova-plugin-wkwebview-engine on cordova ios 4.0.1
any solution ?

**Comment by EddyVerbruggen** [comment]
That's not this plugin.. this one doesn't support cordova-ios4+. Perhaps in a while, but not right now.

**Comment by matrixreal** [comment]
that's okay thank you
but i still have performance and lagging issue with cordova 3.9.2and this plugin :(

**Comment by EddyVerbruggen** [comment]
Depends on what you're doing, but if it's just too much for a webview you'd better consider something like [NativeScript](https://www.nativescript.org/).

**Comment by matrixreal** [comment]
lagging become huge when i use admob banner

**Comment by matrixreal** [comment]
cause performance are pretty good on cordova ios4 and what thinking to add your plugin to boost it
