### ISSUE TITLE
framerate webgl - extremly low

### ISSUE THREAD

**Issue by ddennis** [Telerik-Verified-Plugins/WKWebView#227]
Hi 

I am using PIXI (a canvas/webgl render).

I have verified the following: 
- that i am rendering on WEBGL
- Xcode prints "Using a WKWebView"
- CPU on device is using 3% messured in xcode
- the frame rate is messured through stats.js (but also visible to the human eye)

Still the framerate never goes higher than 17 -20 frames per second.

I am using ionic and running the app on a iphone 6+, tried building through Xcode and ionic ios run.
The same app running on a Nexus 5X - runs a constant 60 frames per seconds.

Any help will be much appriciated.

/Dennis

**Comment by EddyVerbruggen** [comment]
Doesn't sound like something I can influence but can you share the app?

**Comment by ddennis** [comment]
Thank you for getting back so fast.

I will try to build a demo version and share that, was hoping i just had to set a flag in xcode or somewhere. It seems funky that it dosent just use alittle more cpu to boost the framerate, seems like it's been throttled down.

/Dennis

**Comment by andreialecu** [comment]
Does it work properly in Safari on the phone?

**Comment by ddennis** [comment]
Hi

@andreialecu - sorry i did not think of that.

It's the same problem with Safari browser:
- Safari frame rate 15-20 fps.
- Chrome on IOS frame rate 15-20 fps.
- Chrome on Nexus 5X - 55-60 fps.
- Chrome on Nexus 5 (phone from 2014) - 55-60 fps.

I understand that then this can't be related to your plugin.
Any feedback on what to look for?? 

Thanks 
/Dennis

**Comment by EddyVerbruggen** [comment]
Good call on the Safari check. I guess you better ask the pixi folks then, sorry.

**Comment by ddennis** [comment]
Thanks for helping.

For reference i tried switcing to a canvas render, which made the framerate go to 55 Fps.

I am still researching but it could be that i need to make all assets power of two, to get the performance from webgl.

/Dennis
