### ISSUE TITLE
black screen problem

### ISSUE THREAD

**Issue by matrixreal** [Telerik-Verified-Plugins/WKWebView#229]
Hi,
i got black screen with that log
started http daemon:http://localhost:12344
when i remove the plugin the app work

**Comment by matrixreal** [comment]
any help ?

**Comment by EddyVerbruggen** [comment]
Any more details will help. Like device, cordova-ios version, etc

**Comment by matrixreal** [comment]
device iphone 4s and iphone 5
ios  9.1 and simulator
cordova ios 3.9.2

**Comment by matrixreal** [comment]
i'm using construct 2 to made my html5 app
it work without the wkwebview plugin

here is the content of the index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Cigar.io</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<link rel="apple-touch-icon" sizes="256x256" href="icon-256.png" />
	<meta name="HandheldFriendly" content="true" />

	<style type="text/css">
		* {
			padding: 0;
			margin: 0;
		}
		html, body {
			background: #000;
			color: #fff;
			overflow: hidden;
			touch-action: none;
			-ms-touch-action: none;
		}
		canvas {
			touch-action-delay: none;
			touch-action: none;
			-ms-touch-action: none;
		}
    </style>
    
    <script>
        function abc() {
            showInterstitialOrVideo();
        }
    
    // window of the iframe
    var innerWindow = document.getElementById('my_iFrame').contentWindow;
    innerWindow.abc= abc;
    
        </script>
</head> 
 
<body> 
	<div id="c2canvasdiv">

		<canvas id="c2canvas" width="640" height="960">

		</canvas>
	</div>
	<script src="jquery-2.1.1.min.js"></script>
	<script src="cordova.js"></script>
	<script src="c2runtime.js"></script>
    <script>
		jQuery(window).resize(function() {
			cr_sizeCanvas(jQuery(window).width(), jQuery(window).height());
		});
		
		document.addEventListener("deviceready", function ()
		{
			window["c2iscordova"] = true;
			
			// Create new runtime using the c2canvas
			cr_createRuntime("c2canvas");
			
			document.addEventListener("pause", function() {
				cr_setSuspended(true);
			}, false);
			
			document.addEventListener("resume", function() {
				cr_setSuspended(false);
			}, false);
			
		}, false);
	
    </script>
</body>

**Comment by EddyVerbruggen** [comment]
Do you mind sharing your app with me? I mean, all the relevant sources so I can deploy it and see the problem.

**Comment by matrixreal** [comment]
@EddyVerbruggen 
yes of course
here is a simple game example https://www.dropbox.com/s/jrlf0s9qmoaie94/example.zip?dl=0

**Comment by matrixreal** [comment]
@EddyVerbruggen 
any news ?
thanks in advance

**Comment by EddyVerbruggen** [comment]
Isn't it sunday in your timezone? :)

**Comment by matrixreal** [comment]
@EddyVerbruggen 
YES :dancer:  you got reason ... sorry ... we like to work on sunday

**Comment by EddyVerbruggen** [comment]
Haha I can relate to that ;)

**Comment by matrixreal** [comment]
@EddyVerbruggen 
any newsabout my issue ?
strange cause it work without your wkwebview plugin
thanks in advance

**Comment by EddyVerbruggen** [comment]
It's so awesome I have to find compatibility issues in other people's libraries (C2 in this case).

Change line 3454 in `c2runtime.js` to `this.isWKWebView = false;`

**Comment by matrixreal** [comment]
@EddyVerbruggen 
Hi,
thanks a lot it work perfectly
but it doesn't work with this wkwebview plugin  https://github.com/apache/cordova-plugin-wkwebview-engine
do you have any idea ?

**Comment by EddyVerbruggen** [comment]
No.. perhaps for that plugin you need to change the line back to what it was.

**Comment by matrixreal** [comment]
@EddyVerbruggen 
with your changes and with the original line it still the same

**Comment by EddyVerbruggen** [comment]
If you're using https://github.com/apache/cordova-plugin-wkwebview-engine then please ask over there..

**Comment by matrixreal** [comment]
@EddyVerbruggen 
hi
thanks for your help but i did not find where can i post my issue
