### ISSUE TITLE
mailto: "unsupported URL"

### ISSUE THREAD

**Issue by lorensr** [Telerik-Verified-Plugins/WKWebView#242]
Hi 👋😊 Thanks for all your great plugins! 

I upgraded both to latest Cordova and to WKWebView. After upgrading, tapping my mailto link gave a missing `<allow-navigation>` error in XCode. After adding `<allow-navigation href="mailto:*"/>` to `config.xml`, there's no XCode error, but there is one in Safari remote console:

```
Failed to load resource: unsupported URL     mailto:foo@bar.com
```

Asking about it here because one of the only other mentions of this error I could find was in #5

**Comment by EddyVerbruggen** [comment]
Hi 👋 !

Have you tried it like this? `<a href="mailto:foo@bar.com" target="_blank">call!</a>`

**Comment by lorensr** [comment]
Thank you, kind sir! 

This showed a blank in-app-browser-like thing before taking to mail client:
`window.open("mailto:" + vet.email, '_blank');`

So I used this instead:
`window.open("mailto:" + vet.email, '_system');`

Also I don't need the `<allow-navigation>` rules anymore 😊
