### ISSUE TITLE
Can't uninstall the plugin

### ISSUE THREAD

**Issue by cotufaloschiflones** [Telerik-Verified-Plugins/WKWebView#246]
The plugin is just valid for ios9 and cordova 3, I'm using cordova 4 and I'm getting a error in a header file when I'm trying to compile. The problem came when I tried to uninstall the plugin, it has a dependency (cordova-plugin-webserver) And if I run "cordova plugin rm com.telerik.plugins.wkebview" I'm getting the error: 

```
Uninstalling cordova-plugin-webserver from ios 
Error: Uh oh!
Path must be a string. Received undefined
```

Of course, if I try to uninstall directly  cordova-plugin-webserver i'm getting the error:

```
The plugin 'cordova-plugin-webserver' is requeired by 'com.telerik.plugins.wkebview', skipping uninstallation.
```

Any help here I'm stucked because of this...

**Comment by kristfal** [comment]
Delete the wkwebview folder in your `/plugins` folder, then `cordova platform rm ios` followed by `cordova platform add ios`
