### ISSUE TITLE
PBG build error

### ISSUE THREAD

**Issue by vespino** [Telerik-Verified-Plugins/WKWebView#264]
I'm using this plugin: https://www.npmjs.com/package/cordova-plugin-wkwebview

When building I'm getting the following error which refers to a non-existing plugin: "Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: com.telerik.plugins.wkwebview"

Is WKWebView still supported or is it EOL? I have tried https://www.npmjs.com/package/cordova-plugin-wkwebview-engine but this results in errors in my jQuery Mobile interface.

**Comment by EddyVerbruggen** [comment]
Check your config - are you pulling this from npm or phonegapbuild?

**Comment by vespino** [comment]
NPM.

**Comment by EddyVerbruggen** [comment]
Please show your `config.xml` and we'll figure it out.

**Comment by vespino** [comment]
I have attached the config file in a zip file.

[config.zip](https://github.com/Telerik-Verified-Plugins/WKWebView/files/608210/config.zip)

**Comment by EddyVerbruggen** [comment]
LGTM!

You said: "...is causing the build to fail.." do you have the PGB buildlog?

**Comment by vespino** [comment]
[build.txt](https://github.com/Telerik-Verified-Plugins/WKWebView/files/608357/build.txt)

**Comment by EddyVerbruggen** [comment]
Thanks. You can't use this plugin with Cordova-iOS 4 (needs 3), so downgrade Cordova or use a different WKWebView plugin.
