### ISSUE TITLE
Speed of calls

### ISSUE THREAD

**Issue by rogercrandall** [Telerik-Verified-Plugins/WKWebView#268]
Here is my current setup, and I am only able to send 2-3 emails a second. How can I speed this up?

In the same setup, I am able to send 100+ per second on sendgrid, so I know its no the database query that is slowing me down. Thank you in advance for any help. I am relatively new to using github, so I apologize if this is the wrong place to ask this.

```
$ses = new SimpleEmailService(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
$ses->setBulkMode(true);

while(){ // i run through a database
		
	$m = new SimpleEmailServiceMessage();
	$m->addTo( $email );
	$m->setFrom( $from_name.' <'.$from_email.'>' );
	$m->setSubject( $subject );
	$m->setMessageFromString( $textBody,$body );
	$m->addCustomHeader('List-Unsubscribe: <'.$unsubEmail.'>, <'.$unsubLink.'>');

	try {
		$ses->sendEmail($m,$use_raw_request = true);
	} catch (Exception $e) {
		echo $e;
	}

}

$ses->setBulkMode(false);

```

**Comment by EddyVerbruggen** [comment]
Are you sure this is the right repo for your question? Smells like a question for Amazon to me...

**Comment by rogercrandall** [comment]
Well my account is limited to 150 calls per second if thats what you mean. So I am just trying to figure out where the bottle neck is. Does this way allow for a persistent HTTP connection?

**Comment by EddyVerbruggen** [comment]
Let's take one step back please. Is your question regarding speed of http calls in WKWebView as opposed to the regular Cordova-iOS UIWebView? That's something you can easily test by removing this plugin and running the same code. Can you share the metrics? In any case, there's nothing we can do to speed up communication over http with your mail service.

**Comment by rogercrandall** [comment]
I appologize.. I have no idea how this happened, but I am in the complete wrong repo.. so sorry

**Comment by EddyVerbruggen** [comment]
No worries mate, good luck!
