### ISSUE TITLE
 'Cordova/CDVLocalStorage.h' file not found

### ISSUE THREAD

**Issue by fabriek-huis** [Telerik-Verified-Plugins/WKWebView#271]
When I run my app with com.telerik.plugins.wkwebview plugin says  'Cordova/CDVLocalStorage.h' file not found?! 

Full Error - 
`ProjectName/platforms/ios/LudeiTest/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.m:4:9: 'Cordova/CDVLocalStorage.h' file not found`

**Comment by bahaaador** [comment]
did you figure out how to fix this issue?

**Comment by fabriek-huis** [comment]
@baha2r Sorry no i didn't. Check Cordova's plugin for me its the best one (even better then Ionic's version).

**Comment by bahaaador** [comment]
thanks for your response @sputn1k , do you mean [this ](https://github.com/apache/cordova-plugin-wkwebview-engine) project?

And to give you some perspective I've inherited a cordova project that uses this plugin and I obviously wasn't able to use this with Cordova 7 and if I remove this plugin, none of the local files "file:\\\" would not load when I build and run the app. I don't even mind if it falls back to UIWebView, I'm just trying to make it work with the new Cordova, thought you might be able to give me some insights as all the different versions and discussions are making it a bit confusing for me to figure this out, thanks again.

**Comment by fabriek-huis** [comment]
@baha2r yes thats the one. I have latest Cordova (7.0.1) works for me. WKWebView is pretty buggy you might as well use UIWebView for production.

**Comment by mityaiko** [comment]
it does not work with ios platform > 4.x

**Comment by fabriek-huis** [comment]
I also tried downgrading at the time I didn't work for me.

**Comment by jhoanborges** [comment]
i'm currently facing the same problem
