### ISSUE TITLE
XHR for local files is failing

### ISSUE THREAD

**Issue by limitedmage** [Telerik-Verified-Plugins/WKWebView#35]
XHR for local files is failing after adding this project. This breaks [KnockoutJS components](http://knockoutjs.com/documentation/component-overview.html) that we use in our app.

The exact error is:

`[Error] XMLHttpRequest cannot load file:///private/var/mobile/Containers/Data/Application/appid/tmp/www/path/to/file.html. Cross origin requests are only supported for HTTP.`

**Comment by EddyVerbruggen** [comment]
@limitedmage can you send me your project so I can take a look? eddyverbruggen at gmail dot com.

**Comment by micky2be** [comment]
Might be a "feature request" but we really need this.

**Comment by IjzerenHein** [comment]
I just found a solution for this.
It seems that the `persistent` directory maps directory to the apps `Documents` folder.
And `Documents` can be accessed through the local webserver using (`/Documents`).

So, this:

`cdvfile://localhost/persistent/bv-content/js/bf9a967a-vendor.js`

Would become:

`/Documents/bv-content/js/bf9a967a-vendor.js`

**Comment by allenbriggs** [comment]
I second that @IjzerenHein good find!
