### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by lylepratt** [Telerik-Verified-Plugins/WKWebView#38]
When accessing external URLs from the WKWebView, it seems to include `null` as the Access Origin. Is there some way to set this to `localhost:12344` or something? I am unable to access ANY files from S3 because of this, even if `AllowedOrigins` is set to `*`.

Error:
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
Failed to load resource: Cannot make any requests from null.
```

**Comment by vogloblinsky** [comment]
I re-activate this issue.
I have a CORS issue with this plugin, but for me Access-Origin is not null.

```
XMLHttpRequest cannot load http://timeo3.keolis.com/widget/xml/arret.php?idwidget=4&arret=californie&pivk_ip=http://timeo3.keolis.com/relais/105.php&alea=1422379179461 

Origin http://localhost:12344 is not allowed by Access-Control-Allow-Origin.
```

**Comment by lylepratt** [comment]
You'll need to add "localhost:12344" to your CORS allowed origins.

**Comment by vogloblinsky** [comment]
I am not the owner of the backend endpoint.
The same stuff works fine in normal Cordova webview.

**Comment by lylepratt** [comment]
Because WKWebView is serving files using a local webserver, the file:// protocol is not used, and just CORS must be used instead. If you don't have control over the server, you are SOL unfortunately.

**Comment by vogloblinsky** [comment]
I know, may be a native http call through a plugin could be a workaround, but not very usefull.

**Comment by revolunet** [comment]
@vogloblinsky a workaround is to setup a simple http proxy that adds CORS headers for you. ex: https://github.com/gr2m/CORS-Proxy

**Comment by EddyVerbruggen** [comment]
I'll add that proxy link to the readme, love it!
