### ISSUE TITLE
keyboardDisplayRequiresUserAction doesn't work

### ISSUE THREAD

**Issue by geppy** [Telerik-Verified-Plugins/WKWebView#46]
I'm not under the impression that it's possible to support this option with WKWebView.  Is it?

**Comment by clauderic** [comment]
This is a huge bummer :/

**Comment by EddyVerbruggen** [comment]
Woah, #184 suggested a fix and after half an hour tweaking it I must conclude it works flawlessly!

The only drawback: it uses an undocumented API, so I hope it will remain working. But it's the only way..

**Comment by jason-engage** [comment]
Does the update only work on iOS9? Or does it also apply to the lower versions as well? (Great update btw)

**Comment by EddyVerbruggen** [comment]
@jason-engage Is there anything that makes you wonder why it would be iOS9-only? AFAIK it's universal.

**Comment by jason-engage** [comment]
Cool thanks, just making sure.

On Tue, Nov 10, 2015 at 2:17 PM, Eddy Verbruggen <notifications@github.com>
wrote:

> @jason-engage <https://github.com/jason-engage> Is there anything that
> makes you wonder why it would be iOS9-only? AFAIK it's universal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Telerik-Verified-Plugins/WKWebView/issues/46#issuecomment-155536256>
> .
>



-- 


[image: ENGAGE] <http://www.engageify.com/>
*        Jason Shaw <jason@engageify.com>*, Director of Operations    Tel.
647 783 7463 | Skype:  jason.engage    en.gg |  <http://en.gg/>Follow us on
Facebook <http://www.facebook.com/engagetheweb>

**Comment by hirbod** [comment]
This won't work on iOS 11.3 anymore. See my fix here
https://github.com/onderceylan/cordova-plugin-wkwebview-inputfocusfix/pull/4/files
