### ISSUE TITLE
Version 0.3.4 Build Errors in AppBuilder extension for Visual Studio

### ISSUE THREAD

**Issue by JoeMeeks** [Telerik-Verified-Plugins/WKWebView#58]
I imported the WKWebView Polyfill plugin into an AppBuilder project targeting Cordova 3.5.0 and the following errors occur:
```
iOS Build Tooling revision 2014.12.19.1
```
```
	Compile: In file included from /tmp/67feb740e5ee49b7ab5ccfd61262f1a0/Cordova350/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.m:1:
Cordova350/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.h:3:9: fatal error: 'WebKit/WebKit.h' file not found
```
```
	Compile: In file included from /tmp/67feb740e5ee49b7ab5ccfd61262f1a0/Cordova350/Plugins/com.telerik.plugins.wkwebview/AppDelegate+WKWebViewPolyfill.m:3:
Cordova350/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.h:3:9: fatal error: 'WebKit/WebKit.h' file not found
```
```
	Compile: In file included from /tmp/7f5ad1914ee64dc9a05fc60a92d7f3b1/Cordova350/Plugins/com.telerik.plugins.wkwebview/ReroutingUIWebView.m:2:
Cordova350/Plugins/com.telerik.plugins.wkwebview/ReroutingUIWebView.h:2:9: fatal error: 'WebKit/WKWebView.h' file not found
```
![vs-build-error](https://cloud.githubusercontent.com/assets/3031672/5574775/37d1757e-8f7e-11e4-9094-96cc16fd92fc.png)

**Comment by zbranzov** [comment]
Hi Joe,
Would you please reopen this issue report as the plugin is still in Beta phase and here is the best place to provide a feedback. Normally, when the plugin gets stable enough you should find it on http://plugins.telerik.com/

**Comment by JoeMeeks** [comment]
Updated my original comment to include the iOs Build Tooling revision # and "fatal error: 'WebKit/WKWebView.h' file not found" from the Server build failure output.

**Comment by JoeMeeks** [comment]
I wonder if the issue with AppBuilder's cloud builds is similar to this known issue with the [Cordova wkwebview-engine plugin documented here](https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine#known-issues).

>When you build, it might complain of a linking error. This is a plugman bug that does not install WebKit.framework properly. Open up your project file in Xcode and add it manually.

>If you are using the CLI, open Xcode by:

>    ```open -a Xcode platforms/ios```

**Comment by EddyVerbruggen** [comment]
Hi,

We now officially support this plugin via our Marketplace portal. Please [read the documentation here, especially the AppBuilder bits](http://plugins.telerik.com/plugin/wkwebview) and reopen this issue if you have any trouble. Or open a new one if it's not related.

A few things to check:
- Use Cordova 3.7.0 in AB,
- Don't use debug builds.

Thanks,
Eddy
