### ISSUE TITLE
CORS Isssue

### ISSUE THREAD

**Issue by cschmidtanexinet** [Telerik-Verified-Plugins/WKWebView#59]
Great plugin!!!  But having an issue with CORS.  My app loads up but all my external AJAX calls are failing.  I tried modifying your plugin to work around CORS but that did not work by using addHandlerWithMatchBlock and adding in the CORS response headers:

[response setValue:@"*" forAdditionalHeader:@"Access-Control-Allow-Origin"];
        [response setValue:@"GET" forAdditionalHeader:@"Access-Control-Allow-Methods"];
        [response setValue:@"PUT" forAdditionalHeader:@"Access-Control-Allow-Methods"];
        [response setValue:@"POST" forAdditionalHeader:@"Access-Control-Allow-Methods"];
        [response setValue:@"origin, content-type, accept" forAdditionalHeader:@"Access-Control-Allow-Headers"];
        
But that did not work.  Here is my issue:

[Error] Failed to load resource: Origin http://localhost:12344 is not allowed by Access-Control-Allow-Origin. (GetListOfJobs, line 0)
[Error] XMLHttpRequest cannot load http://{my web service}?_dc=1420489645738. Origin http://localhost:12344 is not allowed by Access-Control-Allow-Origin. (index.html, line 0)

Any ideas???

Thanks,

Chris

**Comment by EddyVerbruggen** [comment]
I think your best bet currently is indeed using that proxy. Note that Cordova will need to tackle this CORS issue as well, or otherwise developers will still need that proxy (or control over the server).

**Comment by cschmidtanexinet** [comment]
THANKS for your help!

**Comment by EddyVerbruggen** [comment]
NP - Sorry for the bad news.

**Comment by Yashaswini** [comment]
Hello there, 
I too am facing same issue.  I am able to build it for ios and deploy it on device. I see this error in console while I debug it : 

 error Failed to load resource: Origin http://localhost:12344 is not allowed by Access-Control-Allow-Origin. (email, line 0) [Error] XMLHttpRequest cannot load ..... 

What am I doing wrong here?  Any possible solutions? 
Thanks in Advance

**Comment by EddyVerbruggen** [comment]
What have you tried already to enable CORS on the server?

**Comment by Yashaswini** [comment]
In my server I have enabled CORS:

    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
