### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by FlashMapper** [Telerik-Verified-Plugins/WKWebView#67]
Hi, my first comment before in GitHub.

I keep trying this plugin but I keep getting compile errors. I've tried a few times, I've completely rebuild the cordova project, and am running the most up to date version of cordova but it's still erroring.

I looked at the other threads and saw something suggesting I needed to use an earlier version of the plugin but I had similar. If this is something I'm doing wrong on my part I apologize but I'm at a wall.

![screen shot 2015-01-26 at 12 05 54 pm](https://cloud.githubusercontent.com/assets/5245147/5904079/f42cf582-a553-11e4-92c0-cd9188427afd.png)

**Comment by EddyVerbruggen** [comment]
Hi Jim,

How are you building your project exactly?

Perhaps you forgot to run `cordova prepare` after adding the plugin?

**Comment by FlashMapper** [comment]
No, I did prepare. I still have the terminal up, I took a screenshot.

If I remove everything publishes great. If I add again everything breaks.
![screen shot 2015-01-26 at 9 20 53 pm](https://cloud.githubusercontent.com/assets/5245147/5912375/491dd3a2-a5a1-11e4-9d34-2d4bc67d8260.png)

**Comment by EddyVerbruggen** [comment]
Hmm, what version of Cordova-iOS are you on?

Also, can you try with a brand new project? Create it, add the plugin, run `cordova build` and see what happens?

If nothing works feel free to send me your XCode project at eddyverbruggen at gmail dot com.

**Comment by FlashMapper** [comment]
I will give it a shot at lunch and check the iOS cordova version. Thank you.

**Comment by FlashMapper** [comment]
I made a new build and the plugin worked. I'll start from there and try to rebuild to see where it goes wrong.

**Comment by FlashMapper** [comment]
That worked. I have no compile errors at all and have rebuilt everything, re-added all plugins. I only did not re-add icons / splash screens yet because I have to go call into a meeting.

The performance is perfect. I haven't seen it perform this well since before iOS6. Thank you so much!

**Comment by EddyVerbruggen** [comment]
Excellent, thanks for letting us know :+1:
