### ISSUE TITLE
Errors when used in AppBuilder projects

### ISSUE THREAD

**Issue by tjvantoll** [Telerik-Verified-Plugins/WKWebView#68]
This plugin causes AppBuilder builds to fail and I'm not sure why. You can recreate this on a simple example:

```
$ appbuilder create hybrid hello-world
$ cd hello-world
$ appbuilder prop set FrameworkVersion 3.7.0
$ appbuilder plugin add "WKWebView Polyfill"
$ appbuilder build ios
```

Here's the error I got: https://gist.github.com/tjvantoll/45fc3e28f8f3e0f44524.

Any idea what might be up? cc @rdlauer

**Comment by EddyVerbruggen** [comment]
Hi TJ,

That last command build with the debug profile which is not compatible with this plugin because the LiveSync feature of AB seems to use the same embedded webserver as this plugin (GCDWebServer).

So changing the last command to this should work:
```
appbuilder build ios --release
```

**Comment by tjvantoll** [comment]
Ah, ok. Next time I'll read the documentation :)

I'm wondering if we should make this warning stand out more prominently. Currently it's hidden in a big list. If nothing else, we should recommend that people use the --release flag during the plugin install.

**Comment by EddyVerbruggen** [comment]
Ha, didn't know that was even possible with the CLI, excellent suggestion, I will update the doc. Thx.

**Comment by tjvantoll** [comment]
:+1: Thanks again.
