### ISSUE TITLE
Cordova Media Plugin

### ISSUE THREAD

**Issue by FlashMapper** [Telerik-Verified-Plugins/WKWebView#69]
I couldn't find another comment on this, but once I turned my iPad volume back on I realized that the audio wasn't playing on the app. I'm using the cordova media plugin to play audio files. In the xcode console I'm getting messages saying it can't find the audio files. If I pull the WKWebview plugin this works again.

![screen shot 2015-01-27 at 3 36 22 pm](https://cloud.githubusercontent.com/assets/5245147/5926605/49d153e8-a63a-11e4-964d-5c6564744fb5.png)

**Comment by EddyVerbruggen** [comment]
That's a new issue indeed. Can you post your html/js showing how you're trying to load the file so I can try to reproduce it?

**Comment by FlashMapper** [comment]
Sure. The media plugin wants different paths for Android and iOS. The path in the console is correct (it's pieced together from a set of variables).

Android requires a different pathing solution. I left in in there in case the WKWebview causes a similar issue and has a different base directory in the media plugin.

```
var playSound = null
if(deviceType == "Android"){
     playSound = new Media("/android_asset/www/"+MYAPP.utilityAudio.bufferedSoundArray[MYAPP.modelApp.selectedTopic][tokenSet.indexOf(piece)], doneSound, errorSound)
}
else{
     playSound = new Media(MYAPP.utilityAudio.bufferedSoundArray[MYAPP.modelApp.selectedTopic][tokenSet.indexOf(piece)], doneSound, errorSound)
}
playSound.play()
```

**Comment by EddyVerbruggen** [comment]
Hi Jim,

The problem is the fact that WKWebView does not allow loading files from the local filesystem (the `file` protocol). This is what the Media plugin tries to do.

What this plugin does to circumvent this problem (to load files from the local www folder) is running an embedded webserver, so files are loaded off the `http` protocol.

As a workaround you can try this for iOS: `new Media("http://localhost:12344/"+MYAPP...`

**Comment by FlashMapper** [comment]
Thanks. I'll give it a try after dinner.

**Comment by FlashMapper** [comment]
That worked! I guess I'll have to either publish for iOS8 only or put in another conditional saying if it's iOS7 or below use the unaltered pathing.

Thanks!

**Comment by uipoet** [comment]
You could also use the file plugin like so:

```JavaScript
var
  path = window.cordova.file.applicationDirectory + 'www/filename.mp3';

window.resolveLocalFileSystemURL(path, function (fileEntry) {
  fileEntry.file(function (file) {
    var
      media = new window.Media(file.localURL);

    media.play();
  });
}, function (error) {
  window.console.error(error.code);
});
```

**Comment by FlashMapper** [comment]
I might try the file plugin as well. Now that the webview performance is better I can see Media plugin is also having an iOS8 issue for me. After the sound plays sometimes it pauses the whole app to release the media clip.

Thanks!

**Comment by JoeMeeks** [comment]
uipoet, I believe your answer is the best solution I've seen. Using the file plugin works like a charm on iOS 8 in a WKWebView and is perhaps the correct way to handle a media resource than relative paths or http://localhost:12344/ hack.
