### ISSUE TITLE
PushPlugin issue

### ISSUE THREAD

**Issue by kas84** [Telerik-Verified-Plugins/WKWebView#72]
There's an issue when using PushPlugin on iOS because it's calling the js functions in the webView not in wkWebView. How can we make it call the wkWebView?

Here's the exact line where the plugin is calling the webview javascript engine:
https://github.com/phonegap-build/PushPlugin/blob/master/src/ios/PushPlugin.m#L221

**Comment by EddyVerbruggen** [comment]
Hi, [this method](https://github.com/Telerik-Verified-Plugins/WKWebView/blob/master/src/ios/ReroutingUIWebView.m#L7-L11) is exactly what solves that problem. It's been around in the plugin for a while, and I just tested it with the push plugin. After receiving a push and I tap it, my app opens and the push message is shown.

Can you test without the WKWebView plugin by uninstalling it, or [renaming this method](https://github.com/Telerik-Verified-Plugins/WKWebView/blob/master/src/ios/AppDelegate%2BWKWebViewPolyfill.m#L14) to something like `dontload`?

**Comment by kas84** [comment]
You're right. It was my mistake, Xcode wasn't loading the changes in my JS. Thanks for the help!
