### ISSUE TITLE
App now asking twice for location permission

### ISSUE THREAD

**Issue by jvence** [Telerik-Verified-Plugins/WKWebView#73]
We are developing an app that requests location permission. When we added this plugin, it now asks twice for permission to access location information. The first permission shows the app name along with the message to allow or not. Once we allow, it prompts again but this time instead of the app name is shows: "http://localhost:12344" Would like to use Your Current Location

We using webview, it only prompted once and showed the correct app name,

**Comment by EddyVerbruggen** [comment]
Interesting issue.. Will take a look soon..

**Comment by jvence** [comment]
Any update on this? Also, any update on Apple fixing the bug causing the need for such a plugin?

**Comment by EddyVerbruggen** [comment]
Just tried this again on my iPhone 6 running iOS 9. At least when using `cordova-plugin-geolocation` (and waiting for `deviceready` to fire before using it(!) you'll only get this prompt (once):

![img_5283](https://cloud.githubusercontent.com/assets/1426370/9989962/5e1f975a-605d-11e5-976f-721818b6e56c.PNG)
