### ISSUE TITLE
index.html in inside folder and reloading of webview

### ISSUE THREAD

**Issue by mrozyckiYDP** [Telerik-Verified-Plugins/WKWebView#74]
Hello!

I got this code:

- (BOOL)application:(UIApplication*)application openURL:(NSURL*)url sourceApplication:(NSString*)sourceApplication annotation:(id)annotation
{
    if (!url) {
        return NO;
    }
    
    NSString* jsString = [NSString stringWithFormat:@"%@", url];
    // all plugins will get the notification, and their handlers will be called
    [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];
    NSArray *substrings= [jsString componentsSeparatedByString:@"/"];
    NSString *urlString = [substrings lastObject];
    
...
[some Url processing and making request];
...   
 
    [self.viewController.webView loadRequest:reqObj];
    [self.viewController.webView reload];
    return YES;
}

I placed it in your appdelegate for 8.1 but it not reload page and self.viewController.webView seems to be a UIWebView object. What shall i do to make it load my URL?

**Comment by EddyVerbruggen** [comment]
You need to load the url in the wkWebView instance, not the webView. But I'm guessing this is not really Cordova related?
