### ISSUE TITLE
Plugins not found

### ISSUE THREAD

**Issue by TheBikingViking** [Telerik-Verified-Plugins/WKWebView#75]
Hi

I just tried to utilize this plugin, but I'm receiving a lot of "plugin not found errors". More specifically for Device, StatusBar and SplashScreen. The errors manifest themselves as "CDVPlugin class CDVStatusBar (pluginName: StatusBar) does not exist."

Those three are the only plugins utilized at boot, so whether or not the other plugins we use work or not is hard to say.

I'm using Cordova 3.6.3 and the 3.5 version of this plugin.

**Comment by EddyVerbruggen** [comment]
I guess you've solved this by now ;)
