### ISSUE TITLE
3d-transforms?

### ISSUE THREAD

**Issue by hessius** [Telerik-Verified-Plugins/WKWebView#78]
In my app I'm using a dynamically added 3d-transformation and experiencing some weird behaviour...

**Steps-To-Reproduce ("S-2-R")**
Dynamically add css-class containing the following code

```css
    -webkit-transform: rotateX(360deg);
    transform: rotateX(360deg);
    -webkit-transition: -webkit-transform 0.6s ease-in-out;
    transition: -webkit-transform 0.6s ease-in-out;
```

**Actual Results**
Element goes white for 0.6 seconds.

**Expected Results**
Element spins in 3d around its x-axis for 0.6 seconds.

**Platform**
iOS 8.1.3, iPhone 5s

**Additional Information**
No error-msg. Works fine without WKWebView
Same result with rotateY.
scaleX works fine.

**Comment by EddyVerbruggen** [comment]
Hi, just tested this in the default cordova CLI generated 'hello world' app and couldn't reproduce it on the iPhone 6 simulator.

I added this in the default index.html: `<button onclick="this.className='spin'">spin</button>` and added your styles to a class `spin` in the default index.css file.

Perhaps some other CSS class is preventing the animation from playing nice, so you may want to try and isolate the problem. It could be a 'backface visibility' rule.. but that's just me guessing.

**Comment by hessius** [comment]
Thanks for checking it out, weird since it works in the browser as well as without wkwebview. Won't be investigating further though. Unfortunately I experienced some other weird behaviour with clicks through elements and some weird layout issues, harder to track down and since I didn't notice a clear performance boost I'm putting this on hiatus for awhile 

Thanks though!
