### ISSUE TITLE
Deviceready not firing in PhoneGap 3.7.0

### ISSUE THREAD

**Issue by michaelargast** [Telerik-Verified-Plugins/WKWebView#79]
Hello there,

I can't get my deviceready to fire when I use PhoneGap 3.7.0 under iOS 8.1.3.

Can anyone confirm this issue with the WKWebView?

Regards
Michael

**Comment by jrouault** [comment]
I had the same issue for Cordova 3.7.0 under iOS 8.1.1. ```gap://ready``` was failing.

Downgrading Cordova to 3.6.3 fixed the issue but I'll need to make it work on Cordova 3.7.0 and up too.

**Comment by EddyVerbruggen** [comment]
Are you perhaps using an older version of the plugin? Or there's something else in your code causing the trouble..

I just created a new Cordova app with the CLI with these steps:

```
cordova create wkwebviewtest
cd wkwebviewtest
cordova platform add ios@3.7.0
cordova plugin add https://github.com/Telerik-Verified-Plugins/WKWebView
cordova prepare
```
And then added an alert in index.js.

The result was this:

![schermafbeelding 2015-02-27 om 13 20 00](https://cloud.githubusercontent.com/assets/1426370/6412400/90d11326-be83-11e4-9a21-27cda82494c8.png)

**Comment by jrouault** [comment]
We apparently had remaining files from an older version of Cordova due to a previous install. Removing the iOS platform and re-adding it forcing Cordova to 3.7.0 did work.
This is no longer an issue, at least on our side. Thanks for your answer!
