### ISSUE TITLE
cordova Camera plugin url inaccessible

### ISSUE THREAD

**Issue by machinemessiah** [Telerik-Verified-Plugins/WKWebView#81]
Cordova version: 4.1.2
WkWebView plugin version: 0.3.5
Camera plugin version: 0.3.6-dev

When using the cordova camera plugin with WKWebView, I can use the url returned for a photo (using the navigator.camera.DestinationType.FILE_URI format, which returns the filepath of the image) for use with the FileTransfer plugin and upload it just fine to my server, but if I try to use that same photo url for populating either a background-image or an image src, it shows nothing. However, if I have the camera plugin return the navigator.camera.DestinationType.DATA_URL format, I can use that as an image src or background-image just fine, but because the data uri for any photo is so long, I cannot use this format for uploading or posting to the server.

This leaves me with a bit of a dilemma, since I need to both show the user a preview of the image they have selected (this counts for videos too), but I also then need to upload that image/video, and as it stands with version 0.3.5 of the WKWebView plugin, I can't do both.

I have tried using the regular file://[whatever] path returned by the camera plugin, as well as replacing file:// with cdvfile:// and also replacing file:// with http://localhost:12344/ to no avail.

**Comment by timcash** [comment]
Would converting the dataUrl to a Blob and then attaching that Blob to a DataForm do the trick in the mean time? That is how I solved a similar problem.

**Comment by sunylyons** [comment]
Would you mind terribly explaining how you made this work? I can't seem to get the Blob idea to cooperate with Cordova Camera / Cordova FileTransfer.

WKWeb View performance is amazing. This is the single issue I can't sort out for integrating w/ my Ionic app. FILE_URI stubbornly refuses to render in the img ng-src when attached to a $scope. DATA_URL works fine for the image preview but not FileTransfer.

Any explanation of how you solved would be greatly appreciated!

**Comment by sunylyons** [comment]
Please...the problem remains and I have no work around. How did you solve? Does anyone else know a fix?

**Comment by rajatrocks** [comment]
Did anyone ever figure this out? Any guidance on how to show the image preview locally would be much appreciated.

**Comment by timcash** [comment]
you should be able to show a DATA_URL by setting it as the "src" attribute on an img tag. As for loading it up to a server I used

```
ClientUtils.dataURLtoBlob = function dataURLtoBlob(dataURI) {

    var byteString;
    var arrayBuffer;
    var intArray;
    var i;
    var mimeString;
    var bb;

    if (dataURI.split(',')[0].indexOf('base64') >= 0) {
        // Convert base64 to raw binary data held in a string:
        byteString = atob(dataURI.split(',')[1]);
    } else {
        // Convert base64/URLEncoded data component to raw binary data:
        byteString = decodeURIComponent(dataURI.split(',')[1]);
    }
    // Write the bytes of the string to an ArrayBuffer:
    arrayBuffer = new ArrayBuffer(byteString.length);
    intArray = new Uint8Array(arrayBuffer);
    for (i = 0; i < byteString.length; i += 1) {
        intArray[i] = byteString.charCodeAt(i);
    }
    // Separate out the mime component:
    mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
    // Write the ArrayBuffer (or ArrayBufferView) to a blob:
    return new Blob([intArray],{type: mimeString});
};
```

to convert it over to a blob and then attach that to a form submit

**Comment by rajatrocks** [comment]
Thanks @timcash! My current solution uses FILE_URI (I should have mentioned that), and everything works fine everywhere else except for the preview part with WKWebView, so I'm reluctant to mess with it. 

Just figured out how to get the preview working with FILE_URI, using https://github.com/Telerik-Verified-Plugins/WKWebView/pull/88 - just take the file URI that you get from the Cordova Camera plugin which looks like "file:///var/mobile/Containers/Data/Application/67A37225-A408-4685-9A1C-7B879EA43CDB/tmp/cdv_photo_010.jpg" and remove the "file:///" part at the beginning: 
```
imageURI.split("file:///")[1];
```
Set that as the image src and it seems to works great. I tested it on iOS8 and iOS9 with plugin v0.6.0.

**Comment by rajatrocks** [comment]
@EddyVerbruggen - you can probably close this now! Thanks for adding /tmp!
