### ISSUE TITLE
Black Image Screenshot

### ISSUE THREAD

**Issue by yogesh2022** [Telerik-Verified-Plugins/WKWebView#83]
I am using this (https://github.com/gitawego/cordova-screenshot.git) plugin with WKWEBVIEW, I am getting a Black image as a screenshot.  If I remove this plugin then everything works fine.

**Comment by EddyVerbruggen** [comment]
I'm able to fix this with a PR to the screenshot plugin repo, but out of curiosity: how do you show the black screenshot in your app?
