### ISSUE TITLE
 cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true); is no work

### ISSUE THREAD

**Issue by ckken** [Telerik-Verified-Plugins/WKWebView#85]
cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

**Comment by admmasters** [comment]
Seconded - this is pretty key.

**Comment by hussfelt** [comment]
Related #27

**Comment by hussfelt** [comment]
We are seeing the same issue

**Comment by fungilation** [comment]
+1. A key plugin we are relying on for consistent mobile UI.

**Comment by Wenape** [comment]
+1

**Comment by etiennea** [comment]
+1 :-/

**Comment by promactkaran** [comment]
+1

**Comment by clauderic** [comment]
+1

**Comment by enricodeleo** [comment]
+1

**Comment by aemr3** [comment]
+1

**Comment by rumit91** [comment]
+1

**Comment by itkin** [comment]
+1

**Comment by 1nsaneinc** [comment]
+1

**Comment by woniesong92** [comment]
+1

**Comment by hussfelt** [comment]
Should this issue be closed now that https://github.com/Telerik-Verified-Plugins/WKWebView/issues/27 is fixed?

ping @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
@hussfelt If you can confirm that the problem in this issue is fixed then please feel free to do so.

**Comment by hussfelt** [comment]
@EddyVerbruggen will try and confirm this when we do another sprint-test with WKWebView and ping you to close. I can't as I did not create the issue :)

**Comment by clauderic** [comment]
I can't confirm regarding the ionic keyboard plugin, but as for `cordova-plugin-keyboard`, Keyboard.hideFormAccessoryBar() still does not work

**Comment by chriswessels** [comment]
+1. We really need this.

**Comment by andreamaioli** [comment]
+1

**Comment by berndartmueller** [comment]
+1

**Comment by andreialecu** [comment]
For anyone reading this, it has been fixed recently in https://github.com/cjpearson/cordova-plugin-keyboard/commit/33cbbd9c5b93ba5a1d4be8ff19f8fa8b5f76c2f0

**Comment by hussfelt** [comment]
This is pure gold!

**Comment by cjpearson** [comment]
To add on to the comment from @andreialecu, that change has now been published to npm in 1.1.3.

**Comment by EddyVerbruggen** [comment]
Thanks @cjpearson - adding a reference to https://www.npmjs.com/package/cordova-plugin-keyboard-ams to the readme.

**Comment by cjpearson** [comment]
Thanks @EddyVerbruggen, that's a different fork though. The one with the fix is here: https://www.npmjs.com/package/cordova-plugin-keyboard.

**Comment by EddyVerbruggen** [comment]
Thx, doc fixed.
