### ISSUE TITLE
CORS Requests Require Additional Headers Beyond "Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by bradwestness** [Telerik-Verified-Plugins/WKWebView#87]
I'm not sure if this is something specific to WkWebView or just an underlying behavior of Safari on iOS 8, but I see a few other issues on here that might be related.

Even setting an HTTP header of `Access-Control-Allow-Origin: *` on the web service my app hits isn't enough to satisfy WkWebView that it's OK to do an AJAX request against it, though it works without WkWebView and on iOS 6/7 and Android. In order for WkWebView to successfully perform AJAX requests against my web service, I had to set two additional HTTP headers:

```
Access-Control-Allow-Headers: Accept, Origin, Content-Type
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
```

After setting these, my AJAX requests magically begin working in WkWebView. As I said, I'm not sure if this is something particular to WkWebView or just a Safari on iOS 8 behavior, but it's probably something that should be documented at any rate.

**Comment by EddyVerbruggen** [comment]
Point taken, I've added a note to the readme as well as a more elaborate note to the [official doc at the Verified Plugin Marketplace](http://plugins.telerik.com/plugin/wkwebview).

Thanks,
Eddy
