### ISSUE TITLE
Not working on iPhone 6 plus?

### ISSUE THREAD

**Issue by JayLIJS** [Telerik-Verified-Plugins/WKWebView#91]
We are experiencing very laggy performance just on iPhone 6 plus. The rest of the devices are all great (iPhone 4S to 6). Any idea what's the problem?

Thanks.

**Comment by EddyVerbruggen** [comment]
Hi, I'll have an iPhone 6 Plus available next Monday so I hope to be able to reproduce it then. Is there anything I need to add to the default Cordova app in order to reproduce the problem?

**Comment by JayLIJS** [comment]
Hi Eddy, 

We don't have an iPhone 6+ so can't do testings on our end, but we just used very common plugins for our App. Plugins that we use are:

WKWebView
BarcodeScanner
phonegap-facebook-plugin-0.10.1
cordova-plugin-local-notifications
cordova-plugin-geolocation
cordova-plugin-inappbrowser
cordova-plugin-splashscreen
UniqueDeviceID
Custom-URL-scheme

I don't think it's because of the plugins since they work on iPhone 4s to iPhone 6.
Just not working on iPhone 6+. 

Thanks a lot for your help!

**Comment by EddyVerbruggen** [comment]
Hi, thanks for the details but I'm a bit confused: is the entire app not working, or is it slow?

Also, can I get my hands on the app so I can test it on the 6+ I arranged today?

**Comment by JayLIJS** [comment]
Hi Eddy, the App is working, its just very slow and laggy on iPhone 6+.

Our App is only launched in Singapore AppStore currently.
https://itunes.apple.com/sg/app/sovou-social-vouchers/id963068004?ls=1&mt=8
You'll probably need to change to the Singapore Appstore in order to download.

Thanks.

**Comment by JayLIJS** [comment]
Hi Eddy,

Were you able to reproduce the problem?
Any solution to it?

Thanks.

**Comment by EddyVerbruggen** [comment]
No, I haven't been able to reproduce it because I need the code, not the app itself. Is that possbile?

**Comment by nitzanwilnai** [comment]
I am also seeing laggy performance only on iPhone 6 plus using this plugin. Don't have code but I can make a sample app if needed.

**Comment by kaansoral** [comment]
WKWebView didn't function in my texting environment due to network issues, but I've interestingly experienced something similar with Crosswalk + Android, the default webkit performance somehow was less buggy and much faster

**Comment by Jay-Li** [comment]
Hey nitzanwilnai, I think we might be experiencing the same problem. I'm making a HTML 5 game too. Using Construct 2. Maybe its a problem with Canvas.

My solution was to enable WebGL for the game. That solved the lagging issue for iPhone 6 plus. Previously we had some issues with WebGL so we didn't enable it. Took us awhile to fix the issues though. All the Best!

**Comment by nitzanwilnai** [comment]
Hi Jay-Li. How did you enable WebGL? Are you still using WKWebView after enabling WebGL?

**Comment by Jay-Li** [comment]
It's a feature with the Game engine, so I just switched it on. 
Not sure about your game engine though.

Depends on projects. The normal UIWebview that Cordova uses already supports WebGL for iOS, so some Apps I'm using UIWebView instead.

**Comment by nitzanwilnai** [comment]
Ah, I am assuming you are using some engine like Cocoon JS that has its own WebView implementation. That is why turning WebGL on in your engine solved this problem, since it was no longer using WKWebView. UIWebView does not support WebGL.

**Comment by Jay-Li** [comment]
Nope, I stopped using CocoonJS. Too restrictive.
Since iOS 8, WebGL is supported. Doesn't work on the older versions, but it's ok.
WKWebview only works on iOS 8 too.

I'm just using plain Cordova.

**Comment by nitzanwilnai** [comment]
So I am confused as to what you mean by switching WebGL on. WebGL is already supported on both WKWebView and UIWebView. What engine are you using? Is it using a different WebView now?

**Comment by Jay-Li** [comment]
I'm using Construct 2 game engine.
it is an option for us whether we want to use Canvas or WebGL to render.

We are using the default UIWebView that Cordova supports.

**Comment by nitzanwilnai** [comment]
I picked up an iPhone 6 plus to test this. I do not think the problem is with this plugin.

The problem happens on UIWebView without the plugin as well on iOS 8.4.

The new iOS 9 public beta fixes the problem on both WKWebView and UIWebView!
