### ISSUE TITLE
jqm issue 405 method not allowed error

### ISSUE THREAD

**Issue by vivekmago** [Telerik-Verified-Plugins/WKWebView#92]
I was trying it on a jqm app but when I try and do a changePage which tries to load another html file from localhost:12344/xxx.html it fails with a 405 error. Failed to load resource: the server responded with a status of 405 (Method Not Allowed). I am not sure which method is it failing on but seems like the local webserver fails the request from proceeding.

**Comment by EddyVerbruggen** [comment]
Interesting case, can I get a hold on your project perhaps?

**Comment by vivekmago** [comment]
Sure I will try and get a sample and send it out..
