### ISSUE TITLE
Not working with screenorientation Plugin?

### ISSUE THREAD

**Issue by RedEars** [Telerik-Verified-Plugins/WKWebView#93]
Hello,
very nice plugin. It seems to work fine on my project, except the screenorientation lock. 
I have the plugin net.yoik.cordova.plugins.screenorientation (http://plugins.cordova.io/#/package/net.yoik.cordova.plugins.screenorientation) installed to lock/unlock the screen orientation. After installing the WKWebView Plugin, the screenorientation Plugin has no effect (does not lock/unlock orientation). 

Any ideas?
Thanks

**Comment by EddyVerbruggen** [comment]
Can you try it by commenting out this line?
https://github.com/yoik/cordova-yoik-screenorientation/blob/master/src/ios/YoikScreenOrientation.m#L83

**Comment by RedEars** [comment]
I have no access to the Plugin File because I am using Phonegap Build :-(

**Comment by EddyVerbruggen** [comment]
Hi @RedEars, ah that sucks.. that's a feature I love of Telerik AppBuilder: while it's a cloud based solution to build your apps, you can always change the native code of plugins if you need to.

Anyway, I forked it for you, made the change, and published it to the Cordova plugin registry so you can use it at PGB. Include this in your config.xml:

```xml
<gap:plugin name="net.yoik.cordova.plugins.screenorientation.wkwebview" version="1.0.0" source="plugins.cordova.io" />
```

**Comment by RedEars** [comment]
@EddyVerbruggen Thank you so much, it works!! Is it possible to create a similiar plugin for Android? As the browser is very slow

**Comment by EddyVerbruggen** [comment]
You' welcome.

For Android there's Crosswalk, and with Cordova 4 we'll get self updating webviews. Beyond that there's not much I can add.

**Comment by RedEars** [comment]
Checked it again and now it stopped working. When I open the app, only a black screen is visible. Removing the net.yoik.cordova.plugins.screenorientation.wkwebview plugin fixes it. Idk why it worked in the morning

**Comment by EddyVerbruggen** [comment]
Perhaps you now resumed the app instead of a cold start? Try killing the app first and start it again to see if that makes a difference. Not that that is a fix for your problem of course.

**Comment by RedEars** [comment]
It also happens when killing the app and starting it again. I can't even debug it with Safari because it breaks before. 
Is the order of the plugins in the config of Phonegap Build important?

**Comment by EddyVerbruggen** [comment]
That's shouldn't matter. But the plugin code is not executed when your app loads, only when you invoke it via 'screenOrientation' (or is that what you're doing when the app loads?).

**Comment by RedEars** [comment]
When the App loads I make screen.lockOrientation('portrait'). 
When replacing your screenorientation plugin by the original one the App starts, but the lock/unlock  functions don't work.

**Comment by RedEars** [comment]
FYI: In the Safari inspector are 2 Files (about:blank and my index) but none of them is inspectable (empty, can't reload ressources)
