### ISSUE TITLE
Got Build Failed Error

### ISSUE THREAD

**Issue by duynguyen0511** [Telerik-Verified-Plugins/WKWebView#94]
export IPHONEOS_DEPLOYMENT_TARGET=7.1
Undefined symbols for architecture i386:
  "_GCDWebServerOption_Port", referenced from:
      -[AppDelegate(WKWebViewPolyfill) startServer] in AppDelegate+WKWebViewPolyfill.o
  "_OBJC_CLASS_$_GCDWebServer", referenced from:
      objc-class-ref in AppDelegate+WKWebViewPolyfill.o
  "_OBJC_CLASS_$_MyMainViewController", referenced from:
      objc-class-ref in AppDelegate+WKWebViewPolyfill.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

I am using 
* Cordova 4.3.0
* Platform ios 3.8.0
* com.pushwoosh.plugins.pushwoosh 3.4.10 "Pushwoosh"
* com.telerik.plugins.wkwebview 0.3.5 "WKWebView Polyfill"
* org.apache.cordova.console 0.2.13 "Console"
* org.apache.cordova.dialogs 0.2.10 "Notification"
* org.apache.cordova.inappbrowser 0.5.4 "InAppBrowser"
* org.apache.cordova.statusbar 0.1.8 "StatusBar"

Any ideas how to fix the error ?

**Comment by cantecim** [comment]
i run into this problem too. I was able to build with the plugin i removed it built to iPhone 6 and then added the plugin again to building for another phone then suddenly run into this problem

**Comment by EddyVerbruggen** [comment]
Make sure the checkbox on the right is activated for the files XCode is complaining about:

<img width="523" alt="screen shot 2015-09-20 at 17 07 09" src="https://cloud.githubusercontent.com/assets/1426370/9986744/9cabd44c-6040-11e5-9b63-ef69b6784fb1.png">
