### ISSUE TITLE
File Not found on Telerik Appbuilder

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/WKWebView#96]
Have never been able to get this build in any project.  Simply created new project, added WKWebView plugin in app builder and built.  I get this errror:

Log:
Compile: In file included from /tmp/19d8c25361e64e52800085962848dbf9/Cordova350/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.m:1:
Cordova350/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.h:3:9: fatal error: 'WebKit/WebKit.h' file not found

**Comment by EddyVerbruggen** [comment]
Hey @frigon you need to change the Cordova version to 3.7.0 in AppBuilder. This will ensure the platform will select iOS 8 SDK when building your app. Sorry if this was not clear before.

**Comment by frigon** [comment]
Thanks but no 
![2015-04-15_11-03-00](https://cloud.githubusercontent.com/assets/5033564/7165866/21637582-e35f-11e4-9948-8ff7bf9eea75.png)
such luck.

**Comment by EddyVerbruggen** [comment]
You actually made it 1 step further. This time you're a victim of the big fat yellow banner issues [here](http://plugins.telerik.com/plugin/wkwebview). TL;DR: you need to disable LiveSync/debug at the moment.

**Comment by kwanchanok-wc** [comment]
i have same error.i already set cordova version to 3.7.0 and set disable live sync , but still error

**Comment by kwanchanok-wc** [comment]
what shoud i do fix that problem. i found when i try to deploy to iPhone

**Comment by kwanchanok-wc** [comment]
![upload 4](https://cloud.githubusercontent.com/assets/866304/7956959/0eb1c972-0a0e-11e5-82ff-387c98d23d1a.png)

**Comment by EddyVerbruggen** [comment]
@kwanchanok-wc do you have an AppBuilder project I can take a look at?

**Comment by kwanchanok-wc** [comment]
@EddyVerbruggen  what file do you want to look at?

**Comment by kwanchanok-wc** [comment]
i found this error

Error: [xcode-build] Link /tmp/builds/c1NQazl21v9IKTCwTx/app/DerivedData/Cordova370/Build/Intermediates/Cordova370.build/Release-iphoneos/Cordova370.build/Objects-normal/armv7/Cordova370: duplicate symbol _OBJC_IVAR_$_GCDWebServerHandler._matchBlock

**Comment by EddyVerbruggen** [comment]
Your issue originates from the fact that the WKWebView plugin uses an internal webserver which is also used in another plugin (or AppBuilder LiveSync). This collides.

We're currently fixing this problem on our side, but to fix this problem right now I'd like to take a look at your project. And in case you're building with AppBuilder please build in 'release' mode.

**Comment by kwanchanok-wc** [comment]
if i change to release mode it can deploy to iphone,but i need to debug program

**Comment by EddyVerbruggen** [comment]
Exactly - that's what we're trying to fix. Will keep you posted, just build in release mode for now. If you want to debug temporarily disable (remove) the plugin.

**Comment by kwanchanok-wc** [comment]
i need to debug program with WKWebView plugin that why i need this plugin for debug mode
