### ISSUE TITLE
Breaks custom URL schemes

### ISSUE THREAD

**Issue by jayniz** [Telerik-Verified-Plugins/WKWebView#98]
great plugin - it breaks launching the app with custom url schemes though (using [this plugin](https://github.com/EddyVerbruggen/Custom-URL-scheme)). I've also filed an [issue there](https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/78), not sure which plugin needs fixing :)

Does any of you use custom url schemes to launch your app and also WKWebviews? If so, how?

**Comment by EddyVerbruggen** [comment]
Hi @jayniz thanks for reporting this.

Custom URL Schemes didn't work indeed, but will work with version 0.3.7 of this plugin which I will release later today.

**Comment by jayniz** [comment]
![](https://dl.dropboxusercontent.com/u/1953503/gifs/4zZ49hw.gif)

**Comment by EddyVerbruggen** [comment]
![giphy 1](https://cloud.githubusercontent.com/assets/1426370/7238524/529ee774-e7a3-11e4-94f1-fd43f0e756c1.gif)
